// Code generated by "esc -o data.go -pkg fake data"; DO NOT EDIT.

package fake

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/data/en/adjectives": {
		name:    "adjectives",
		local:   "data/en/adjectives",
		size:    138,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/xzMwQrCMBCE4fvAPFQhUj0ZrHiPyVoW0kbWDb5+aU4D38A/qRGzVGLq3ojY/mLEM62n
FH1XIa6BmONyvuZpUNBfJi5VsptmIop9mm1pz0IsWoR4aZFG3PZvd+LefWxQk+zEQ7bmI7Sqp0ocAQAA
//+zr8RPigAAAA==
`,
	},

	"/data/en/characters": {
		name:    "characters",
		local:   "data/en/characters",
		size:    108,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/wTARQ3FAADA0HuTevkMcsbMPPV7gYQSSSyJpJJJLoWUUkktjbTSSS+DjDLJLIusssku
h5xyk7s85CkvectHvvKTv1wBAAD//1QUwj9sAAAA
`,
	},

	"/data/en/cities": {
		name:    "cities",
		local:   "data/en/cities",
		size:    5314,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1xYX5IiuY9+J4I7+AKzdyioKuge6GKBqYp+FJkiU4PTypVtaPpWe4a92IZkJ8z8XvAn
pf/IkvxZ5qVFDyHxfPbScRZwa/I+zmcvHgZsQcEJwl3bHoaTmIYiu0/Cv3WUT1lABwzQsrglJe08oFAD
wS0h3DnMZy8BeqRBQYsSi6pDH90ShlGFRNz089nLOHp0n+A96jzSQEtQQLJW+M5uJRBaVDFhLN+vpHMm
iA20KGpZ6lGSrZRukFDms5d8yqKKK3j7cMUAfj57+Z0jzGcLuKDEM6FvVfDtjYLbgVxUCoFCp0Bi4tt8
tkDIA4ekyPvy61YgLYZYpLPnm666QP/oeMUWBRUGatTwBcoFba8LvKL4+xSABXVugSBuAxc0sTNt7Hmc
zxY+4/TF31OvrUB7ynI3dCtTCoL9hnRj1k0JxRME7Z3Re/POImOAaZtZThAK8BQ6GHA+W4KHE0QN8hI8
/qKGDdGZJRDUkKtiQHWjohGSUMUxcWdwACHvbbBmRbV/CSMl9tZDfDxBa2hA/8fp/kfq8Y8Dlo8jhYR1
2pJDS0g9tgJ+MgIFozVCiRX1xdqewtRMDl72fGt68rZynz24T4qaY0tKkqNbI3V90o4eBEsElx7u5rSl
RxBf7Pd8RWnBV0w6hKHpsUzNYJ5U5M/wy9qhiGUq9pZ9ugPHZ7fkYUBpdDYextolNCzqF5aGBUwlJSGX
LBxgals2lNBt9RiYPiZw2xIZTpBI2yvZGMHYYEiT93ILvbX+ivJQjiipuO8+CsY4n72Cv9fPr6DJw6Te
eYVwJa9+eAVzwyt6twUpYI939wGXogad7xUjSnJrTu4wCgVN8FeCgUPrFjaMQj6Btr/UDa8sYtNydDvw
bPAWNNNfM0jShfPJKxG85hCHTDKfvUFM1tu9eKW5N++W8LdOpwhDkqosOWN4y0Ene/PugF0OrWkvbiV8
VfWAcq8bfQsNBUp6Nt5iU1jlLTYcWrJRSd38lgUv2v5Co6F3ILFMMFDo5l0zXmKd9h0llIx6J+8HFkOC
J8hdP5+9s488aBsS6ArvLMktBLqu4u8c9CAozqVDTI+QvnMOCSg8aPadb94Mm/L8XTBqhN6z95VEV+CT
/irBTZ4oEsxnK/LC9/ls5bHabYg1AVfsMVkbfoNXq4y93RFFQNN8JRDjw5aVIIbqlJVQW5V6xpQP9Y5Y
ZWjB51HH5phI+WwN/uy2zMEt4K5iONuJWcMNiCA8qXkNt9SzlEH3G1gvBN/GU5ZO8YBJG2mymbtGGTjC
tPoa41hYaE2tOqPyyZq63kPQ2VRxYmEL1pq9cqD6d80+1Qivc9cbha1zSBS6pJbXBZ6awsrrLNrz22Dr
+ieaRnwLrW7xC80QlfjJJ99Cm2PSe+Fb6DyWi+Ab6/6/6a1p7Y1q3L5Fjxbv79BczMA/UQZlnD8pdDWB
FFZvbcAt4f/+F1pw755CEmo7NPUarFqY0JNPNxMdKSCBtsAdGC0qymjnbwPuvzOFVLSfaDHbwBnumMr3
LodHXKpUo1GlH9Rl9A/xi7m1jxd0bz5SsJNl4jsLxlSEkaWi4q0NhAZKCDcglzhmQ6kXvYs3cKvO2+jx
mQ6HCmV6Cg37YKCNmp0buqJyYUEy1G5Xdas5f8Mt6e8ATgeBYUqlHbnRNnSPnTMPyosbjk7rtnL1Fenf
8OEdVWj9hVVYQJg6rqCOuUO5oDb3UNwwXSlb8HTK2g4Dp97u8ahi6CEleCTyFkLCxgYINTxWFEqr5/a3
oftEe1u415Wad71e9TBtlUd051sMnuuJ2GKgM+oIvSm1F3n/oBAVTgJoaCzsvKUYicNUtm65xZgMBOGr
nmYlfegyFtR40NvDbgJ3QMHAVTqh1TCGxZaraLKNWcaKBDqbWYc/zWPpoNCGCcKFs7ZKy+7Qg1Uh2wdJ
E97ms20WIePRHzDabyIOj8LnB2JrwfyBVz2Lk/ZmhvzAmx3hH3gb7aYo8fmh1YQ1N/Daja+gPvmAS8nn
D7iUIChQ0z8ahBBJS++Pv4Hms4+QQJRtPgSCHvzSuqUdgQ8pyftRY/mhrrZIf/wKRrw7aOhMzXRmqgiK
/OBKgVCFR4mgUrHvH9e61QPKES1G9xYTJLSuAi1FLGhQlxr0pGd5BxHK/bWDyG7PJ18GpVTfKDssFccO
E/is9LSjht1eT60J2JYLc0eBzSKKA0/+3VFKlSZ3HrTQ0jwzKNUPO48QIaSaDZNoa/v7wDnpPFpeuRcp
pvLApdXSKWNArdFVek7KUgrqCh6Zt+ObJtoeQtOzW7K0fIWnnButvbqnRtlZg1rFf/r4oTxA0PoSpAMx
htpj6xY+n88GWytS99hqBkRDHNqHi/bY6omv+bq3LFZAYFHdU9NrOaio7bApFL0ndq/26FJUq/Y9jeo1
C015wxgsybrn5mJ14Z77oDVnOap7vZpDN7Hiv8RnEu054oD6LFFUfbxnLYQP0AgMaO/ng9b5YMrgXkLU
V18RFiia7VZDmyx5gvrk4Tpm6XEoF59Kr4QdT3CY5tXCEKwgNUkgNBSbKq7gJKS3nQrfoaFqV3DfGf4n
6/6LEOsa37NaAzkVFz5U+iSLSWCycoMQWpmETNF9nCiOVbEFaaY9GL8/9Akr3MHJV7iHM0w27jXfDE4Z
cFD2EGsTuJcAE1yAnEAeor7J/iVQeoqSf0/4HZ+88chUenTdcjC2KdIOsn8Ie44Vo3lLoDxjD5AjeHsp
HBpO6Vm5HvBZkR0QSuYd8AQx8ci6ZbQK59DD2WqJQvX1GXwgrYf12SYmdUruhRUONNBzFfbwLHoO7LHV
1Dywv4IetQMHtlU4WPl9UA5xz0dNkVfwxFb+HKHnh+ZJjEX+z1xL/+XW6EuHVOnqkLi5VJRb4imgmWIO
DyGE+9Wo+5Dj47V4yMkeJ4J4mc+OcE7z2RF7aHoYqUDd0REHbCxCRxxGj3XSY886V1sfl0c6lXL5yKIm
43x2FGi0o1Agc9ZRcnPRsB6zvu2txfKaP2bx3KgZ9rKYz443DOkeKKBVqHE+++tC0M9nfwWtJ4oNf43l
gvuEBuqmLF5aanxiSFkjoQWsGvZJTeKJqz/J++nfl0/SzAIDms5f4ENOUzv55wssCF+QUMob5wtS5MmZ
X6j10BfG5KZnvgn/pCpV6Hadrd5h0QwUSo1rAtc7+6tHSBOklOzm/CLvCdQZhlIFfDMQ2sjWSesi1TC3
xbsF2VxaidsJ+clyepS5P/WKrjv5WV7NP/Npqmd+5gZoNF3TTNfa/wcAAP//2wxBbsIUAAA=
`,
	},

	"/data/en/colors": {
		name:    "colors",
		local:   "data/en/colors",
		size:    146,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/xTKwarCQAwF0P2F+1HvCRYRsUgRXA6dUEOniU2N/r50dTbnJpX4bylEFyJGPKQ1/xLX
KDYJ0We8mhB39SZv4mRVJycGKY3o1WbimNuohei8VbHwSlxKfoi/NctSQk2IIWNN102IQ+iyue0rfLfP
UYjzs8z6CwAA//97rU8+kgAAAA==
`,
	},

	"/data/en/companies": {
		name:    "companies",
		local:   "data/en/companies",
		size:    3555,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1RXy3LquhKdq0ofRQJJHYhDAlTOhVkbC1vbD7lsyWC+/lavlpyzZ8GW1Y/16M7ubhvr
K602NDutfpxLP3P30OrdlvJHZsxknFZn1+ZBq40djFb72XWFGbRazx09n7NWa9NaHPjX1vb51OqfrnMX
rb7sw3XzQ6tjR72nctTqTK0lrVYTta1Wr6bzVh7k5EmrN2OK1j60eqOCA58qF8rK54MtSrP8xIlVaaeg
1ZYQ4SXkeWPwYm0n6o1WH4Zv51fPZ26owydtTvzNY+z5wbGe+Y63xvajd0Or1cvg7qPJG8q12hSl6UMz
Gq1eXWnRkQ/647Q6GGqWnO6WS9ndbReWDONtfLHrub415WPl/KjVZ0/c6tVEkzFavTSu/N+RL2YkjvUs
Cea5Gca+MsNv1ZLUsbYdV/lVOe8aO3rp9h9q5R2Q2c+OO5DgeCFujnx/qOandQAi5/jcrc65ojHp3Gi8
VifX2+udOPzZFc4xyFPvbOelL3LZ2kxjhUOnIeAUNwp/cF09FSCXJJXNnTeMrH9q9U65D53hp3ngHHc0
g2o7egatfizOokiUlhnDn12cwym8yEOJUrljjMg15Ay7nczNjhVfxZlt0diXwXILQQM+ISAc6znVvjaT
vc0ACgF3FOO1T9fhmgZlCT848rEKt1tjisFOBglCC292Moka75SPvfNaHZxjjvC7a0VeuuOpRICUwW7B
4ZVaWwCjwjQCQEQk8kr44eceifnBgn9QzD9A90cCbukhJR/rheGZZaGxxK9NEEJBgTGlkZvPpbO6J+ai
8XfoPrM5d+A7iIg2Furag6+h7ZnEjDWTM/JXAv4tiWy+u6Ee0XC08cN2dWrYmvKbMQW6KfQ81pYDnAX2
jfjNL/pMRSkDrhS1jFdsPkj4gjJOVArhGFJIeWPR3S09OvLWdZCy92aICf7rhqI3hY22lA6tKb9olQVg
Qg11ZvlwsYQh2iuX0Uoq/e8xUe0evGXdGPCKbDeZgc2GsYlmcagWgjLDbwDiDKuEB0GFW+OjTZ2pFvWd
SMTH/bnHj65miLpMpcCDnFZ7UPuDWIdvDY1VckfbS8SDc49ke1BrFvi3SOvk+qiBT1AaRJXMMmOid7Ri
RE0wT+daJChI7whsyuYr64JJB3BEr4UrGfsg+XAxiHAAhAILsM6MYVtG7tGkzi78R4aTZZi+A0T9HVAU
qwzXrOzvsJPj4iSidVFZFDvCZxYjZ21L63GQDViOYaCBVjx1kP42zkg7Ec8auTQ2jPXikRiGx3egB6Zt
kKHBDIQpHWuL1Ji7V2L2MDZirwJ4zG/07LQsqcZ2TOKleTEEwGlc6Lgx3D+xyr1jeJA92y/fLqX92D7G
RTE87PLIlVmrz3TTMfHO1MLunZhKUpQYiAyA5Adxuh2qWZjJ7hiJJ8XkhryMxCbNgrGnq/SLdcXqwHpR
Uy4MZnh3nCN3i61ANM+Of9Hq3eSxq/IYew+BT8BsJcBe0sTi+cmYwaLAe15TnjILRXGnIeCbPbeN25Q6
ks1iEKXw2kyCmzij8OtYR5tgXUXafgfRAycp45cnJbh1diH6s5j7oZrB2xN0e7C3W3QrGeNCIbgd+iim
iWlwcQ7wne4WAh5CH9kg/c9meNKnhDuZ+tbwafCX4wicPOolf5BKdL2lR7RPLh2zDm5ImPDgzlmavZHq
bEny5TrV+VoRcyY25KvBxnWiMmrC1piNp3vcdS7iTYxRlGotOxo3JK1aMrGK0kBOmY1zFbMym7mbcfeR
IXV2QdyJo6HJvFp5E306UZe3kZAsk7emlZV5cCHcjMOJELKh4rLoQ/LE/8drUieez8akICLSIbr7Hxnu
YkDJ144xSfYccYCvJq53v3vRYq1/L5dszfCW/exAhmUL2cqqvuwHXIwQTgQccT471NK4Mrp0VN9Krj1L
UM4D2zlylJ1xD1Qi3MmseSUrFp+EeKKJpKn1tmSYxi74fYoVS3m/m55ftsLkaLwO/IiPfblC9Em5+NaH
MQ/ZQm0kmUctOH2oZkxKAA4/TDMjrejI5F2e/USCbqSPWP5kVXFxRkOEsmjyZIw7PImo9rNDsJX8awX5
CimZB9j5ZCWMm4KhJnr+htfG/wcAAP//x/xvHuMNAAA=
`,
	},

	"/data/en/continents": {
		name:    "continents",
		local:   "data/en/continents",
		size:    75,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/3Iszkzk5fLLLyrJUHDMTS3KTE7k5QrOL0XmOpYWlxQl5oAUOqZBhFxLi/ILUnm5HPNK
EouSS8BigAAAAP//T+G5V0sAAAA=
`,
	},

	"/data/en/countries": {
		name:    "countries",
		local:   "data/en/countries",
		size:    3022,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1xWS5Lbus6eq0p70OxPqnIWkXa/bXf8t9x96mQGSWgJMQU4IGkfeX5Xdjd2C6TsdmUi
fAQoEm/i+0c/AJMPwGXx3/844K4svrsGmMBAj5rAiEotcFXDKLbmTlQT6MVlGsllFEDbQG3G1EeogLvq
BrSJnTG1Rw7ECY6YL9LYGPEtsifh6snPqkQfFFzaYzCBE2oD9MtUvoEBRvAJKFDicO+gQz8Y1gY6MTE6
0JhBT3FMgE5olNNvqGNS72aIyRk34uhg192IZ8o2PKKesJdDUv5Ggj9CRvGA4aLzjcKJnFEK5IfqnbSn
s0n+k//EHQFXP1oErraoSkF0MnlkpOrWFPbgwJSNrodk/E3UHTFU9+AlrSJ3VBYLGBvpbMMCRlQRNsTQ
Jc4eq3fUDg1PI1zpskA2/1bfP3J8X3EfG0dtWSwG6OxLDhMxQxeDkg8j+IutC2nFV1+WiI64/3rFdzI2
SR8ZRS0EC+Fevl1uqOTjwrvFUVqFQO2fYtld6So+QPWaMmshAavu/54OQmr6qUBIt6U8Wkz7FOzFCdvh
yqZb5BF0Vxa3v6iRGKgsbmUkTkee0bUT7toInWhZ3PXTPpTFnatqcIeZ9ztCECVw1UMkRiiLO6WgCfgg
KbPvwkCyN3QPbmeWnA2qvqzBWSr5ryZUwU9T7+kX2ZezN+8VuEWjyO1gt6W8m5cbcROjp09OLTEMqJ9Z
RejL4gEaS4sHyIF5QNE+Ax2Bp7J4GNKxD9QouABaFg+KaBcbnXV5UMxp9RChQydxjwmP6RtwBJeEqOzR
Dp1dk+lfN+Q9RFtO6bJHIAvDI4J2qcbW7a0wuO7TGY/CXVTIqK+Wwn1ZPEbuwarlqcWsWCqnRGT2xpNa
IT8p/LbveZt3WMlHtU4yr4CuLJ4CuKksnmGElAvPsDfxM2qy4Vm0s/USTrAbcrNcIk9QFktSasBMWIoi
fKteRMNwWaVIlMUyHoFCWSwn7adTPmAFVhUrCKnLrLABtvCs0EsYpCxW1OTmu6JmSgTbISD7gNawVhSG
mNv0Kv6LYyNR+7JYQ2vuXUOLXc7ANXTQg28tnmtwcKRMJ5+lrqODpccaXJaExFY/gHOfUViDBmL6HdFw
VAowH2+YYtoySQgmx3+plbJYU6vnYKzFdXJIgCEJrfZdFnFAxl4zN3hUhWBYpc1bT5a0+e4JrIjL4gVG
Son8AlFjWbzgHpwRS/1Z6atFZY+Rc5i4x2oB7uwgW/5EyOnxQi0o9NH4ZPe9UI86k7Rb9EPc7tLpUryt
1tbWoBk+PfYieoSpLH6MFu4N7OZndgPOQrQBh95cet39v1U/2jbuCTvbwDCC0X2EyrQ819ImqziVxQbN
9M1AjvZ7YrNuQ6EF0s83dCNnqiH25qNNRA1irVTK4v8hlforRiZLwFcZc2Rfo0+Rez0CW8HXQBzsHQ8D
OhynM+cRHfJFvqQQfKrkFzyQP7NXsaXLnpxL59WGUBVz8VuMnVxE78QtckiyMGCVm0+2cx5FasiuZzEs
1VbGfNZGiVuy7lRD7Aiq7wopX2rLNXNDjTozpnbAnBu1KQPVCoXtT+Ie9mJPTO3kALu03ckhjy21vXJy
9ZzWMuZhJdX9/KqeV3PDvRiTuTVwd6R2uDpknwaZWqlaAe/s/5jaTx2VGEZT5gCuOXfM5+SBCa/1ONoI
kqJeH7FD+/lI4ZRroSzqKeXyFuhoB2/hF52zcwt8yvHfDjCfsaVR9K8VeivurfRi3x2mNN4K97ZZiamD
rNFWGkibIlNKoW3UnTVSozbyzVdF3eVUWQDZHHHRfxsP4GJZvPU59d52NtxhWbwxBexSKKu7kRSCBW3m
Lon7TsbLug4mtmY/z69/Sv6czN405rJ6q6s1sWj1IwY3EfdXe+r6tSzeTg2ePfYOHCFEAyHNDwsKU76i
+vIobqpqxK9l8Y6Mp4j2PL4TBrYn829wjrIP7mOI1+3jb3O32sg9gI3a/+Bocfwn9uIdpEfj5/yU/6Sx
geaI/wsAAP//zbzFMs4LAAA=
`,
	},

	"/data/en/currencies": {
		name:    "currencies",
		local:   "data/en/currencies",
		size:    1906,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/3RVzbLiOA/dpyrvoCU8Br+3aeA2H+Gbqe6dkqgTDY7MyPaluU8/pQAJU9WzScXH+jk6
ku3Zz6ZF4RBR4PmfZzNXojDCjs5kq4aUEZYsqLbbkXKFMPm/cKQaioiRwhSW3rm7gTYkkQXhQMEbkEJU
dBZjsDGIEYqqZedYmpBnc2yxwzAazbFVZBkyz1EahzWFFk54RgO0xNq/upBrOHWwVpSqX2uX6pfEc8VP
dnAktErnyTWofakfmGcLFHw1XqxnMF+sZt+GeD2ymi1GoGVHz0IXrVX9PaHAkaRjKTnPjvs5TH6zM82z
hXe+K3kQarE+jIF9iAhHU9rMhAxTj5ERtkmM7e2iKcDBJ6lt85OqFo50SaXjCrZek9zybEnSoZ5hq15I
bZ1iqFqCyRtph3Kbwh71HPJs6TsWrnqKjyAPXssUqxYm7xRbUodShym8JXY1mUorDJFUYIHKZUkoo4Cr
5naJA8NViN7maqveC+fZKqlFX/NfPLqsWSxDT+qMmGe9IDTo8mANQx0P9m/e1fAtSWVCvSlRRbBUrNoO
Kc++WHip/7OGL14a2NpnIPIlSYN6g7VXlphnm4r6ECZk0jzb7NdQXKhidJboytLAkZvWTKVmhGO6kJHZ
SG3tuyOMrUFqKjO6+//fw4hv9J7kKdkmKJKDd7pC0dKZeoeI7gY7Vsqzr9ihjcjA+iteUOA7SZ599Vrj
eHq2JDeEYjxvW6+EMCl8iu0U/vSSZ9t0RY6Dy45KFC8Dm136RV3pkzZDO/bo8NbXxtI0HO9QROPH9p+U
I6cwqLGnX1z552Ttvfqq8rBkbbELefbSn5f2WP0/CHtphlLfvV7xNgz2t27U9IDn+6X2zHpA57C2m+E5
IgfSBO+JPnyAwrseatnx5cJC4cnv4DCyvLp5x6GFH87Hm600pgYdrEKVanP4H0ZUOPKt53H0XX+TGv8d
8QjcFyncp6Ls0xeYaoaZYtnLeY9QsPsgHdIXLA1evNIoQ+H8B57tWD1OvAFkSU7+YWEdhtnP/to+otRP
6D4BfeeLi920BwoU0Vx+N9gBJpv9eppnhTLsUM7jjBfJRu05J8WVapK+M15tyfHz3tRhbk7IV5RemKGS
U4vcG83RTtFJWbjGGgw6+RIb/2KbhMPLq3RKeqb+VGCePV4mkxJWHas9UOOIPXa3LE3tu4H0v56zMdEf
JPSZyCHMveMPVPo9COtEGvtNpijYwdJLk2c/sL/ht1esWsyzfwIAAP//naaT/nIHAAA=
`,
	},

	"/data/en/currency_codes": {
		name:    "currency_codes",
		local:   "data/en/currency_codes",
		size:    648,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/zRSW5KEIAz876o+FBhQh4dswF1n7n+QrTD60xUhIf0wnEqcXYjVN2JxQrhTiFd7E3tV
on6EWLZIfJwSc8LFSricCbHb+YDTfs+60QlvZ34zkEF4b1WIhC9WaSb8Wu+V1xGJy0ViyUajvh84GnE1
u9CF2DQRy9taPomQZBAKIdZX80pcixBhbUQI6aYbX0LEvRBR4z1xuZNYVe6xLQmxnZHYeyIu0Vv+Pis1
+BFiD43Ycyf2kYlXebx6HUKk0Imkf0T6EyKbp9keLW8lik0UI1SuShT3LJ8W1yMRR1GiJTXRQrRQibZN
DwbRsn2OQPxYFHpUg0zo6YluZ5dbib4K0c2cvo87t8kq9HZry7ajizWbTTPfYZzH5okxrKoG+iZceH6Q
mfRv8AaR+LWWT3l8ngl+s7TIvlHMC9Hb8cnvW5miqTKc+h8AAP//ZziIZIgCAAA=
`,
	},

	"/data/en/domain_zones": {
		name:    "domain_zones",
		local:   "data/en/domain_zones",
		size:    1004,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/xTMQc6sIADA4H2THhJQ0VHQEXSenv7lX39pQ5IwSBglTBKyhEXCJqFIqBJ2CV8Jp4Qm
oUu4JPwk/JPwSgwSo8RB4ihxkpglzhIXiR+Jm8QisUrcJZ4Sm8Qu8Zb4k/hIfCUFSUnSIGmSlCXNkhZJ
q6RNUpFUJe2STkmXpFvSP0mPpFeGUYaPDKsMRYZdhlfGJOMoY5ZxlvGUscnYZbxkWmT6yLTKVGTaZTol
B8lR8iB5lDxJzpJnyYvkTXKRXCUfkr+S/7omuUu+JP8kPzKvMheZq8ynzF3mS5ZBllGWTZYiS5Vll+Ur
yylLk6XLZ5RPkc8un0PWUdYs6yzrImuRtcr6Z6esP1kfWV/ZgmxRtiTbItsq2ylbk63Ldsl2y/ZICVKS
lEHKKCVLmaWsUjYpRUqVsks5pHylnFKalC7lknJL+Un5J+Xv+UoNUpPUUeokNUtdpG5Sd6mH1FPqJfWV
vcgR5BjlmOTIcsxyrHJscvx5leOUo8nR5fjJ8cg3yDnKucvZ5Lzk/EkL0qK0JG2QNkrL0mZpi7SPtFXa
Jq1Iq9J2aae0Lu2Sdkt7pL3Sk/RB+iQ9S5+lf6Sv0jfpRXqVvks/pJ/Su/Rb+k/6K1eQK8u1ylXkanI9
cr1yB7mT3KPcWe5F7ir3Jb9Jfk2eUZ4uzyVvkLfI+5P/AQAA//9oSEPX7AMAAA==
`,
	},

	"/data/en/female_first_names": {
		name:    "female_first_names",
		local:   "data/en/female_first_names",
		size:    785,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/0SSy87cMAiF90g8VObS/s1cNJqM2jVJ6BjJwS12fsl9+gonVZfEcDjnIzeyivCgYjIJ
IVxFZ0I4kI1khHCO8odGLgGhZ1X5yYZwI/PeYc2krXqTcUE4JUslVFfJhHAnnSrChYwV4cClVIQPjl4N
pLPrn5IqIRzJUkR4rr5oCGTJhWUKHCMjXGn15oGMAsJFlpEtVoQTj6l96jlnmbwliEWuCMeqJbjLTt8c
CeHGUbLbOhi3jN1S/dXXP3nkyce/i71FfexCJUR2qw9aNgGyEqgttTZOTWYo/CuQCu8pqiIcg0kuoryx
YoSe1AkdqQS29vDFSCfOzQJCn+rECCchf+uieNWv0Wc/uE0hvNg4N2gmGeFrTO0O509uW3umtputRqcX
Z+N5S7Lv7JN3dDk0RP06i/N+prw5bEsvHB3tXaYUm4e5/g+0g6kIr7CbOfDnv2OouNCLFif7zVj34AjX
ZILwJD/oxqQ57nQ23jXNP1zT2jSG9vN1uilMv1eOLcCPjfkhaQPugPx86+g/XXIor2byEWqMXt6TLV7T
6id0vJuuT18lRnEg50U8wDONon8DAAD//7kKvy4RAwAA
`,
	},

	"/data/en/female_last_names": {
		name:    "female_last_names",
		local:   "data/en/female_last_names",
		size:    2013,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/0xV0XIiuw58d5U/CsgCtYENBalL3UdlRjvjwmNxZJvJ5OtPtcxuzstmGcuSWt0tX6ZQ
Ru9+ypiyJO+uIcZAU8anxNm7tcqcvHuhR8jeHUOMrBZm4UcRZe/eaYmi3q1Sz2oH76NMhCzU3VriMRT2
bk+qloi0hGfc3QJ2pF2gPyf85d1ZPkLrahNJb/jQaxgqzg48I82B2bsrxRua2lOM3q1i5OTd/6Wmwbs9
a6LU48prwIerhmEs3h3kjo/7gDuXTkrxbqeMq6veBrAmy7qT9EURsb+4gd6QFpwcQ+lGxv0T67Nh1pK9
e6+aEHEaMc57xp3p/tFiSS3vjwel7N2PfibtESExBny5FJ5Ji3cXSt2IvEdpQzvLwIq/zD0uyM3OBkre
rS35sep9XNB7iLx4dw4PVrLYO4qeQzeinMGQT+/2gvKYIf59F1WQfuLy5HGnhDQ0BUP4kyacX6nY6VpF
btm7V45xsYZ7a/CkoWP0lBJjsFeRHk2pSeosOYOZv2LZSOQJIH5yutkMTqy6eHeS2WAdBNSdqPxpa1+H
Eam2UbQ1lMeQhmJN1WIavYRpEiTbSi7/YdJEvVAq0Ap/Ws/enWvOVmun4fdvSPMlEARCC24cFwO2FYxp
T1OI5TmekSbvLjXG8ACEK8VIAA/MjVb84FxgKe0R8zZzMhqXJBFB25BH00SM4LmZxPKHj+azrpdEEaxr
/TKT5NHk/qYlfAHbZEqpaoRtldtErxwj5sMfHzaR5rVL4Ye18F47E+NJmqT3NbW/oQOvG6X5d4PMCYSs
ZelR/Wl+beN8Bc/9YipSttF9IuBMkzScNvSqKLkT7a2HkWboL5qiziaYp4EawyBoHam7YfukwMBxojg1
6xmsX6EbBf/ZqfH5mpq5t6xDtTRnyQy8kmz5zE1eLzUlE1n7ua/NEZc7p86UQtqbgS+F76NN6kQLUpwC
a5O2CfRIpYw8Z+9WCi4xgiE9N6RxeSabS2mV3v5uEBWw91JTB5ouaenbCoPxNzWlkAZT1lqpNysfCPVX
qVerd67B1Knm6y28fG6eX+mUi5pjNjhujF6ZHgYNO46RblagbaKz9bcZ6QERXQLW36pm29BtFzSPs0mL
0i3i5ECzodkGNhXvagmsbRMuhqobp9CXhte7/1H+x5b3hnIJMQpeBWYz62akuwn2LQbr8yipDDKxLt9b
6/t5Qll7s5rjKUGtR15wcx3yKHd4ppPFNhy3d+FB+r1NTWOUMuS6/X4kdqRfZHN92NBDKfDvumppxqFk
U/g11AVXdyw6sL1z8mFaDz2emsm7bW1v5WFJ3ejdC5MZOkLiVkhtN54BUsypCDtQ23Bbpa9gcKreuPUq
9hBDdpx6QZ9HUU4CX842vSP3IRH0MEfWfwMAAP//njUWyN0HAAA=
`,
	},

	"/data/en/female_name_prefixes": {
		name:    "female_name_prefixes",
		local:   "data/en/female_name_prefixes",
		size:    15,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//ItKtZT8AXhzOJiXi5AAAAA//9bkgxGDwAAAA==
`,
	},

	"/data/en/female_name_suffixes": {
		name:    "female_name_suffixes",
		local:   "data/en/female_name_suffixes",
		size:    30,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//JU8AQhTwXPMIUwBV8XBReXYIWADBcFlzBfXi5AAAAA///UpVYUHgAAAA==
`,
	},

	"/data/en/female_patronymics": {
		name:    "female_patronymics",
		local:   "data/en/female_patronymics",
		size:    766,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/zxSy27jOgzdE+BHOY82cNuLwAlu14zNWprIZEBLCfT3A8rFLC36HJ4He1p4Reg1CMKg
N7aM8BXHQJwQvmNKkRaEAz3jhDD4wCaEfSBLG3DlR0C4Bl1o9YHFNesjsDlKotOcqSSEL7I7wkGF0oTw
zmozI3ywCOeAcMn8ZEE4Tq+2YmeRmqbt/05yUKkOeEZB6GlVcdKcA78Q3skqwjUumkPddCF8kvlrzz8/
xhXhzUjuCJdRc0Y4Whzb3kfwxZ1M5kwD1UXFJRrPahtZKOQ8je7AInFF+KaU3eaZssXxjnDm9n0iU5d8
0DInD+XE4rg9WULoLIdiCEPd7M0O6ZUR+kLNmFN1aauiV6Ec2ntZsxu/biLe2VouHxxberSUf42xm0he
yye9jGVkhP/iGLSpGbQi7Fj+0OJ8Oys+3xnJ5Il2kxd+2pJ7M57caBX/JaZUf4tC+NTiIfRsvFSEjszR
A8lUEU66lXgsMzvUravvLuvKKSHs9HarCP/HMau122jmjia8ZoRzcB8PhKtOky9Zvc69UZw9G8/jEugl
CPtEvw4v7M+OdGA7xO2w/WqOLfs+Lk2rZJWoCH8DAAD//+q0UKz+AgAA
`,
	},

	"/data/en/genders": {
		name:    "genders",
		local:   "data/en/genders",
		size:    12,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//JNzEnl5XJLzU3MSQUEAAD///p9A1oMAAAA
`,
	},

	"/data/en/industries": {
		name:    "industries",
		local:   "data/en/industries",
		size:    5144,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/3RYz3IiPw6+U8U7+JTTpH7PQCDJZCvMUMBOzsItGm3cVq/sJsM+/Zbc/9xMzyWplmxZ
kiV9n3mCQNZsIaIQuLBcrEoh27jYCDizvmBFtpW7piLfVMvFIDSPZgv/YTEbuqIEOhMWy8Wa6xpluXhl
VywXb77AGn2BPpqf5MyDeYWQxE2IeqTZYlRbD2ZLHiWd1Vp98xFLgYhFvvMH+0p3OHW73aH/yZfLxbDM
bIScI1+aB/P8u3YsEIl9vuL5vw3Vlbr1YA4oV7IYcv2OanTkp8I9ntNR6i3IJ8Z07IHcVSM+1GgJXLzl
eTtERN3+Jnr+4ebjBSPZoInypeMKNcTZz9BUKOaVudD817Uj8MnLVRPZbME3Z7CxEZThKjrdDiSG5eIJ
ryhQoqqfBL9Q7oQHPkfNlf+8U3xoZgn1WjYUIjnX7m2CpiTL3nKxphIEY+u0Q0j52QkXjY1tHGe0mv1k
YQMkt0z97NBGYU82t/kCUmWLXpiL+WL7zhWal0Y8hQv5Uv19od+ak6DKJuAXSApjZS2GwBrUcrFFiJn9
n+czWTSHRnOs+h3YTyjbi16zj0Ct9zuoUcyDaf+PBnYogT24XHThyKVAfclD02IbTxFWn7BIFvVELPrr
3qMVTEULrpV9Mz/jRctsovqFF7JOre2b06l1zkFoK+xQs2iJ9kaP+DuSQ/NoVnUNgs6sHcdLKuI/dS/M
8QtB7pN35BNYy0Osg2NHvoXUKFVaJo391O+kzRx9IQ9eG2W5WFlLRZuW7wguXsybD41omS8XqxAwaplD
iV2pOQ5YPD77wrw0Xktig6dZuSY83uY0LyxIpV8u1oIFxaz3s8Iyb/6KIeqpqfzSFrNljzezRh9RzBOk
pul1eyzbC+nkQxzmSfgzFc9os5NBqen+0V3lXxf0ppeLdzpjnqE5h7YssdSNo7VUaTVKvGk5Q2jSjMrs
DOo82fvnt6NmOG+3TtbelQVB8wKWHMVUGL2WI7p/tvp3kI3zfhC1TTd87jGkUsiX7DEC6SeCM88hQkSz
wSs67ubEkPVHs6XicRUd+Ei2z8VU/YUhzmh+sMQLwqxuB5bOs/YO3Px1V9Llpx3g2g2ndwavgkYw3caR
optc6Zja5eKJOKK9eHZc3rQ+ofSsrW0OzSnEDgw20pRmg07v6dZ9/gUbZnVd8ybdHl3C23GMqVhXvaIC
gu0dNGu9/J1L0aQhnMlVEmqKCf/e2ZePR5Sq3ZLXyxYLBUkzQpvC9YgCvf7NhyhNasbJ/Oz173BSgOcO
sPYYEMRexgU7ARtpwKAOp+l/WPRuj1MgYyY98qJwqMHiPxs8ow84D0V/LuuzOGEY66698mmzBXtRhLl1
yJdAR2NOuJmr0zXolGnIFTrZM+bW6xSwNGDWWL8jXG8Tc5MQW/hNScoSny/IkGvNVc2+nYnvTXVC+WY+
FJq7QJPxzllzZHZ/4u5Ye4VReE7QkxigeYGTOtJa2bFzTQr+wRwV7ZILKTJ2qduGaXEX3KEC5+ZP7yEu
H0YfECJO5t6quKJEUtfMqkRv094VydBkSjJ06l9y9NAF/deAiD2UHiLLQNw2CMqmLlSHnK5NF7Wijws7
DOB0GEyJ+kQlDIVV0PelTk0oiP+QHn8pfbuvmomZntxlxbo6/jKHW4hY6RdEcNySX3LmpxQo6RZbvlrV
TdSRkpkcSGyGsliDtNfZB7yhYLnx8Zv5BUI6GAeNDqX8Y2L9uWjaeklFAi0zH08aqeWY21yWW1IEVZaX
/LoDvcQ+s8WvUKXasJGu3STrW29iZ7l4VYInYzh3bHUqf6tq4StOMjPbiJkr/8IvdNkB71yUbUul+bQi
6Z4wY4FnCRqeMLmsG5mzx235Sph1+zdzvKCWkm5stD4fzC8qkAeHBmI8nrBrTq6L/9E8MX/ey37gV6iV
YN8rdijERfeu2gM5rfAcesd49+h1pjyYd4QwjbCHh6mIJc3pta7mVhRBQVmH3QFtI5QAeyeKyanoxv2H
C9V1+xQcnoDPqcUw5LKWzwzTYaDneSlNOfuQyEOE87l9kPxsYuBG7DSsozKFdHWZjNXl73w6jSWSaHny
dbjYkcBnbCOBctde+kz8ainJMCM60RTbuKoa3+/K34jdcDBPoM+dcaL0cr3a+tI9/zcQIfmrNHaDM/R8
etA8hR9sD6fl2mwQ5KTLvPkzS3VvN5c+jDgwv2DM4mRBRPEYJwfshK9UdI+DTt9tmdfNJV0JVnqkp9fG
GkSoa0gXqcKCQN9k7UM0ZFf5A+MXy2f/yM0TOuR8aN9huutjgbxyxDWJbSiaJwYpxtdsqso24227dETy
YEnx+pyGxFisGbfL+mw20ANWZNmrPZb0iwZDYd7J45+67Lejzs8ZAxkPvFfmtCejWJNFj2aLFcvNrFso
H4N66DKQZfuIDi1XQzgKMlyhsvlZ5fBM/SBBpx03uaK7av53HEh1z+hyWf9IzUSvEPLPD40xF/w/AAD/
/2gWXLwYFAAA
`,
	},

	"/data/en/jobs": {
		name:    "jobs",
		local:   "data/en/jobs",
		size:    2360,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/2xV0W6lOAx9R+IfIu0H7Dd0bzvtrKYte6m2z24w4CkkyHHuzNVq/32UECBc5gk4dsLx
iX1yp7X1RtTJWm7IgFguiwV8+InaC11wg844MTo0AgFXf/z38v8aBCN7gEyn7pwjtwuJB76WxV0zkiEn
PO90yNuHX9uWNAZuBgbbqROx9iTqHh11Ro1goFvCVyeqYtsxjGPE1q2f17QNwoZAVQMYsw9UbFt0zs6g
1QSCO9CLHUHIGlVPqAkGcgv5v8i6oJAT0gRmQX3TofyZi5PYLnFHBp1T9dUJjk7d4wUHO41oZEkti1OP
I2kY1IPpyGAgfeoJ20WKDKYL7dIGMnHlxrcsTnYcvSG5qlcvjKD72/CExs11bhzsOHlBXpnuCzlZJ2pr
irK4B4F9iwXkAxyq7Jwtp/X3ob8G9XTtCE2kcajtHt2n2EnVfposi3pD3ZsodohF2XDdjhh12N22qoYB
XVk8NBRpPAyohW/kXN7S8gdzIbZmnEnl4uwjgUJZrDOjatSMEnv9CxkwYZm6ay4U2yeDFlW/WNuoeLzh
6/FrvVQVklj3JKhDAA0yDFszP6IdbHdTRALXM3lkmHrSqUtCxhPCIL062XDmc9ITDlPI+FSvE/J8UhuW
a/zkRzDqjM561ugO43sbX8l+Na3lZW5S92RBQTahXJ8O6G9vyHLuRN+wCwnL/8riG30wcGT1DPyJe9vJ
wfU/z6h7SLOQOGzKzY6QclM5L14PCKwq+wM5y33x7DA9VMWgw8DbKO+r1n6KdYbe6JFhiuc6O9lBsE3w
ChiGUGR4vc7D33z3TuLrboqqHngEHfet+quLFc3/uuYSVGwbryUjnhnZZpWJSgbs57pi+x11ZqP/eBiC
dZysEbb74Vhi2z/PqNmTZK+7QzljaFdkbFSS9YwOgXV/ECsPzM6cYWlxDS3KNWvatDY6QL5wBvYXW1nU
GBvvYGUJXz1mRRZLSZ+/me8UOQqTAkdmNm7wbvkzptlWfgBjkNv5IfFZwBvXWvE3dHIIToi6VxVIn1yi
LGqBtlWHq3yGa01oZMm7vdhqYa/F81os5fOURTNwuTh+Y/9v8HMn+Vu4lcKizQ7fee6jfyu1Xafxc532
+LU0/txkYYAifNO3EUs3wzt+rB6Z+MzQ/k75FQAA//+HpLmJOAkAAA==
`,
	},

	"/data/en/jobs_suffixes": {
		name:    "jobs_suffixes",
		local:   "data/en/jobs_suffixes",
		size:    16,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//Lk5fIEYxARxssFCAAA//+jVevCEAAAAA==
`,
	},

	"/data/en/languages": {
		name:    "languages",
		local:   "data/en/languages",
		size:    918,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/zRSQZIaOwzdu8p36KsAMwPzgfkkUJXK7ASt2AJbomR7COxyoJwiOVjKds+m32vJkp+f
NPuhdAHgZM0sHIEJ2JpZ9KB0smamcOwYcUqlBBETWjO7R1CwZvZAJWvmGEBLaofmyA5CDVIKEMGauaRe
Py/BgU5Ue6cFZAg1svDEPaICuR1aPPDkrXkCptSw3vXk6QN9JSW37EPYXTxY88wutIPPKUu/8YXOEwa6
Ektl3Lu9KHKt/4YpDy9KXf0SHJSHNUsUdT2CGhsq4sWaZQEF/vO7sjMoZLJmBVQFDwtFCWjNCo+KN2tW
xGNNk9KwlVysWRX+dOD1hAF4rA6/8iiMXcCrUvLDEjC0TIbQwv/BFbo9a2CGESpJPlK1ZA0PuHhr1j6i
WrMWxVqzLjq2p67v6u4PazYg9ZM/WssNZV+moW/KT4xHKepawRZOOE4WbiGAg3Tv7BMgQGw0N1Hbv7+k
KtlWR+pwthJG+Wj1wk76I7bCGRmdElvzNuIRq1tveG378oa34R3rMozDnhwPG2BXwNUjotmj8rCX7KX9
37CP53+lO1izgytBRM5SefINUbunO+l7sRPNxZWmeFf4DEey5kvBky9gzVeJkxt7iU3RdNv+Oi3g/gae
WuLW5r6/YTf4AGe6VIgUrDlgKK5UzCVac/BA1hzkMuwo1ZcfkrCDijdgsOY7jb3NewnFmn8BAAD//9TD
DwGWAwAA
`,
	},

	"/data/en/male_first_names": {
		name:    "male_first_names",
		local:   "data/en/male_first_names",
		size:    764,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/zxSy27jOgzdE+BHOY82cNuLwAlu14zNWprIZEBLCfT3A8rFLC36HJ4He1p4Reg1CMKg
N7aM8BXHQJwQvmNKkRaEAz3jhDD4wCaEfSBLG3DlR0C4Bl1o9YHFNesjsDlKotOcqSSEL7I7wkGF0oTw
zmozI3ywCOeAcMn8ZEE4Tq+2YmeRmqbt/05yUKkOeEZB6GlVcdKcA78Q3skqwjUumkPddCF8kvlrzz8/
xhXhzUjuCJdRc0Y4Whzb3kfwxZ1M5kwD1UXFJRrPahtZKOQ8je7AInFF+KaU3eaZssXxjnDm9n0iU5d8
0DInD+XE4rg9WULoLIdiCEPd7M0O6ZUR+kLNmFN1aauiV6Ec2ntZsxu/biLe2VouHxxberSUf42xm0he
yye9jGVkhP/iGLSpGbQi7Fj+0OJ8Oys+3xnJ5Il2kxd+2pJ7M57caBX/JaZUf4tC+NTiIfRsvFSEjszR
A8lUEU66lXgsMzvUravvLuvKKSHs9HarCP/HMau122jmjia8ZoRzcB8PhKtOky9Zvc69UZw9G8/jEugl
CPtEvw4v7M+OdGA7xO2w/WqOLfs+Lk2rZJWofwMAAP//o2W7S/wCAAA=
`,
	},

	"/data/en/male_last_names": {
		name:    "male_last_names",
		local:   "data/en/male_last_names",
		size:    2013,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/0xV0XIiuw58d5U/CsgCtYENBalL3UdlRjvjwmNxZJvJ5OtPtcxuzstmGcuSWt0tX6ZQ
Ru9+ypiyJO+uIcZAU8anxNm7tcqcvHuhR8jeHUOMrBZm4UcRZe/eaYmi3q1Sz2oH76NMhCzU3VriMRT2
bk+qloi0hGfc3QJ2pF2gPyf85d1ZPkLrahNJb/jQaxgqzg48I82B2bsrxRua2lOM3q1i5OTd/6Wmwbs9
a6LU48prwIerhmEs3h3kjo/7gDuXTkrxbqeMq6veBrAmy7qT9EURsb+4gd6QFpwcQ+lGxv0T67Nh1pK9
e6+aEHEaMc57xp3p/tFiSS3vjwel7N2PfibtESExBny5FJ5Ji3cXSt2IvEdpQzvLwIq/zD0uyM3OBkre
rS35sep9XNB7iLx4dw4PVrLYO4qeQzeinMGQT+/2gvKYIf59F1WQfuLy5HGnhDQ0BUP4kyacX6nY6VpF
btm7V45xsYZ7a/CkoWP0lBJjsFeRHk2pSeosOYOZv2LZSOQJIH5yutkMTqy6eHeS2WAdBNSdqPxpa1+H
Eam2UbQ1lMeQhmJN1WIavYRpEiTbSi7/YdJEvVAq0Ap/Ws/enWvOVmun4fdvSPMlEARCC24cFwO2FYxp
T1OI5TmekSbvLjXG8ACEK8VIAA/MjVb84FxgKe0R8zZzMhqXJBFB25BH00SM4LmZxPKHj+azrpdEEaxr
/TKT5NHk/qYlfAHbZEqpaoRtldtErxwj5sMfHzaR5rVL4Ye18F47E+NJmqT3NbW/oQOvG6X5d4PMCYSs
ZelR/Wl+beN8Bc/9YipSttF9IuBMkzScNvSqKLkT7a2HkWboL5qiziaYp4EawyBoHam7YfukwMBxojg1
6xmsX6EbBf/ZqfH5mpq5t6xDtTRnyQy8kmz5zE1eLzUlE1n7ua/NEZc7p86UQtqbgS+F76NN6kQLUpwC
a5O2CfRIpYw8Z+9WCi4xgiE9N6RxeSabS2mV3v5uEBWw91JTB5ouaenbCoPxNzWlkAZT1lqpNysfCPVX
qVerd67B1Knm6y28fG6eX+mUi5pjNjhujF6ZHgYNO46RblagbaKz9bcZ6QERXQLW36pm29BtFzSPs0mL
0i3i5ECzodkGNhXvagmsbRMuhqobp9CXhte7/1H+x5b3hnIJMQpeBWYz62akuwn2LQbr8yipDDKxLt9b
6/t5Qll7s5rjKUGtR15wcx3yKHd4ppPFNhy3d+FB+r1NTWOUMuS6/X4kdqRfZHN92NBDKfDvumppxqFk
U/g11AVXdyw6sL1z8mFaDz2emsm7bW1v5WFJ3ejdC5MZOkLiVkhtN54BUsypCDtQ23Bbpa9gcKreuPUq
9hBDdpx6QZ9HUU4CX842vSP3IRH0MEfWfwMAAP//njUWyN0HAAA=
`,
	},

	"/data/en/male_name_prefixes": {
		name:    "male_name_prefixes",
		local:   "data/en/male_name_prefixes",
		size:    9,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//It0lNwKdLj5QIEAAD//8NLYrQJAAAA
`,
	},

	"/data/en/male_name_suffixes": {
		name:    "male_name_suffixes",
		local:   "data/en/male_name_suffixes",
		size:    38,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//Iq0lMILtJT8FTwBCFPBc8whTAFXxcFF5dghYAMFwWXMF9eLkAAAAD//5A6ShQmAAAA
`,
	},

	"/data/en/male_patronymics": {
		name:    "male_patronymics",
		local:   "data/en/male_patronymics",
		size:    766,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/zxSy27jOgzdE+BHOY82cNuLwAlu14zNWprIZEBLCfT3A8rFLC36HJ4He1p4Reg1CMKg
N7aM8BXHQJwQvmNKkRaEAz3jhDD4wCaEfSBLG3DlR0C4Bl1o9YHFNesjsDlKotOcqSSEL7I7wkGF0oTw
zmozI3ywCOeAcMn8ZEE4Tq+2YmeRmqbt/05yUKkOeEZB6GlVcdKcA78Q3skqwjUumkPddCF8kvlrzz8/
xhXhzUjuCJdRc0Y4Whzb3kfwxZ1M5kwD1UXFJRrPahtZKOQ8je7AInFF+KaU3eaZssXxjnDm9n0iU5d8
0DInD+XE4rg9WULoLIdiCEPd7M0O6ZUR+kLNmFN1aauiV6Ec2ntZsxu/biLe2VouHxxberSUf42xm0he
yye9jGVkhP/iGLSpGbQi7Fj+0OJ8Oys+3xnJ5Il2kxd+2pJ7M57caBX/JaZUf4tC+NTiIfRsvFSEjszR
A8lUEU66lXgsMzvUravvLuvKKSHs9HarCP/HMau122jmjia8ZoRzcB8PhKtOky9Zvc69UZw9G8/jEugl
CPtEvw4v7M+OdGA7xO2w/WqOLfs+Lk2rZJWoCH8DAAD//+q0UKz+AgAA
`,
	},

	"/data/en/months": {
		name:    "months",
		local:   "data/en/months",
		size:    98,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//JKzCtNLKrk5XJLTSqCsHwTi5IzeLkcC4oyc0C8Sl4ur9K8VBCZU8nL5ViaXlpcwssV
nFpQkpqblFrEy+WfXJIPZvjll0GFXFKToSxAAAAA///9St7VYgAAAA==
`,
	},

	"/data/en/months_short": {
		name:    "months_short",
		local:   "data/en/months_short",
		size:    60,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC//JKzOPlcktN4uXyTSzi5XIsKAKxKnm5vErzQEQOL5djaTovV3BqAS+Xf3IJL5dffhkv
l0tqMi8XIAAA//8r/CGtPAAAAA==
`,
	},

	"/data/en/nouns": {
		name:    "nouns",
		local:   "data/en/nouns",
		size:    144,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/zSNwQrCQAxE74F8VC14ES9avC/tKMHdTUlSxb+XVDzNg5nhHaUGjGnUthrc1ZiuHw80
ppvgnd1Ztx5MY3EwDUtZ98fQ1ip3STyYLA9klvmJYDpJME1WujeJfX3BDHklTVv/CXuY1vqXa0dKvgEA
AP//4qrCRpAAAAA=
`,
	},

	"/data/en/phones_format": {
		name:    "phones_format",
		local:   "data/en/phones_format",
		size:    28,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1LWVVaGYV1lZV4uJCYgAAD//3RKfFMcAAAA
`,
	},

	"/data/en/state_abbrevs": {
		name:    "state_abbrevs",
		local:   "data/en/state_abbrevs",
		size:    198,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/xTGQU6AMBBA0f1P/qEmLUqFTg1UEO9/EMPiJS92iU3iT+KQElKGlCl1kY9dPkPWJq1K
26WltJDtlO2RPaQv0qv09016Sj+lD+lTcpG8JFfJL8ku+UgWySpjlbHJOOQ75GhyFjmrzJT5Kz9TrlfI
/brkbnI//wEAAP//tctsLcYAAAA=
`,
	},

	"/data/en/states": {
		name:    "states",
		local:   "data/en/states",
		size:    520,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1SQ3WrcQAyF7wV6h32VsKGNm+5u6U9CLxVb9QjPSos0juM+fZHdQgMGfQdZR3N0V+mF
roRwVymmrC6/TTeYSIMC4UhVfpmrEMLRqjkNlqTKfZN+bgj3XGkhZ4QP1VwGQvjI5mOOPNBCIgjdQMUQ
ulpFTQKh00EoV3W2EMLj33WPrG3upxXhs80S+y8nEuUsvlbSISmC+jIHtxYIJ+mLjKRJqhzWckgi8rvd
ZBc2e5Jp20zP/OJ76jO/0rDV5fBA11sUyTApP7EHrzuf+E162/mn+YRwNm/lcCS3Kpvlpu9p2h5wKWII
l6lSsTzyxXk0RfjCqrHWV9pu+rXYwIcu9mDfbH7nuOt/jt850wVz4lue60ejgvDEfjVtCE/io2y2zxRF
dGy58JmjHf5rSfSmIdlZ7So6/gkAAP//iVeXOQgCAAA=
`,
	},

	"/data/en/street_suffixes": {
		name:    "street_suffixes",
		local:   "data/en/street_suffixes",
		size:    152,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/ySKwQrCQAxE7wPzUaUeRDwULXgONUgwZCG7raxfL62XmffgDe7aiWHTWJUYNZomMVou
vntZsxFjllotXsQpbVPibO7EZY2lWQniKqHEJPn+70f6DrUSk8uix32FmIpFI25FnsS9pWojZs08ojnF
nHhI/wUAAP//r011XZgAAAA=
`,
	},

	"/data/en/streets": {
		name:    "streets",
		local:   "data/en/streets",
		size:    4661,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/0xY3XriPA4+53m4h9zC/u/plLYwUzJlSb/2WCQi8RfHyso2lF79Pq8cZvbEek1sS9a/
+UtM69VfQ7de/U279ervaViv/oHhnxj+heHfGL6dWPv16ls7sq5X33wvE4FOgnF2gderbxOrayn8RtW3
iL2T2BGhY42Cz2Egn0ADTaSjIXdhjaQ3TNLAEfTLhd74Kc00CHio+5IA1jpSiIRlOrmYXGtfVa4iHVBy
0URJyw855SlUe6bzevVAHVMGDZ0LPYCebkYCp2QgsV+A8x5SP1AczgItPVB0HsS23KLreL164KKbB3b+
nGME8r5XueCj03Yogjx4aseT0wJNcQ8+c/XgvK8Opg3M/7TDfeaYeFqvHuR0HVzCYgnB+Mh1wgUf5Iaj
lMNy0wd1pNVGGaZ9UNeOUcL9ZJVrWEi5eGbvjQSq3l1MhMngjUP2qbDIYWStdq4sDWnZqjij+ihcM3SP
W+eUWM+OfXefhJzWqw15R6Ev6DZHAZhO6rqeAYPZfkN6Yl1Q5wJ5Q1x+cNKSgZlDgogbii1B+5v7DwMp
hNqowASbgVVGxoLBBZHRACyy8aQ8SUgLDB1svPH4DRu9lFW3jqsteU/9YOdLB1HEs2lmI16UOjGUp1PG
VpkotAMbmlhbZ5cQqI1DKhPxy71FT2wHacfekSG7vmhsBdJJShKKaWHUlkOqXmmMZZqqvfnQRuXqTU2w
7UDapfXqkQbPIKPAsI80uwCi10IvrgO52uQWE6mBBFU88knJSMTYelJKrnzxVW1L2VeNeAN0JWVDnjoJ
wbaG4Gyz8gjyaSZ6dNVelJMAXlwsZ7pPI8LFdOZhjxIIXvQoWkSSlByYyIUTIQQfla/Q1qPeOqjxMY/4
nkPx7ser64e0Xj1RD2s9Ue/5HhlPdB+9KQCoaPmp7zl0pPjse1z0yTux2UgYpxLxT9PE+FUh01NsB4yW
A54urJZHAHpliPb0OSvDJ5/J6WJAwCVSAC+Or0De35FOrRhV6hFEz6RXC9hn7IpJYPpnF8f16tmLckAW
fIYvTUbtpoVWj+T51+SYg+FoJnm+h8Jz9hb6z9mbxre2Z0uqLpZ54isy05bVTLN1sPTWU+t+ZYith/ps
o/iO70l3K34Zq41kjbxM3u2uW5HOEwrRVqnlX5A79gYCEvRWKcaRptngbaDrCGQKNlIdS1xt1U0Y5YLr
bLOPjBq0I1SMXXGHHXlvKWtHoazbUbBrFmpf9CRwhB1yjq3II8YLQm1HN7ZFX+zbousdk/Hh85k1GBf2
DB3tWCdT1s71w/85+c6F9MXr1U4INWEnPJsP7eR8thyzE4h5v9hO/FRq8U787Z7ndjJxcd6dyLL9Ah/d
5a7cKH9advjuGS7zPXQ8c+iKw3xH7gwW3chO3+VK69UPssIBEGx6W69+cHBnnP6DLcJ/yBCqD4LRAcvy
jAz5QnAtqPCFLGZfuPsqNAS2FRygAHOzF14S3IvzvmNweIH9Xlzo40JK6X1xIZpWXtzsTX8vISdj/KIy
n9erPVXP4j0nFMs9jbw4GGDxKqDC7o6qLWln0u7Jsu+essLv9pYa9qwdDd6A4KuDv+2RWwbJkSvrBPbO
o8IBhA4mGgosa1PyXD17zrpe7YVndcgXezmn2Ita8dmLueVeUIu6UgX3EvqSDPYiE7LpXtLAF+cRX/vc
3VW4z+NonDK2gpbQ3t/MkWtq52Fpv2rqUWvgBzU5+8F7cz4AAduaQqc02orgklwdGrmagjlRTSGfqU1Z
We3s2fNClm6gJm1tobrAGquNVdOa9L+5GKYmvRVr1HSDnDXdlkxY061Yp27RHWBx24pOrh0B++xQaGqm
7ndULLN3yzq/J0Va9qdCrHbX7FWiLfMXuz1Polaja3QBKJQ1B5kkOFul7UDIjTWrFhmKaWqOkTW2w+Q6
+2zNU+3awZkda3c+e2PgSlKtnb9Stm6kdqkdLJHX0o4u9KUhrGXRiQSHTqeWkCz6ANi6oFpCntjkkXIN
0VLsFlCqeC1ox0CjC8ZRlpReZ4fvN03Q1U+aeKQeH35SgM1+sjcv+ckX6gj0Wm1QJbFaToiKn6JIckYW
oxkuwhucLWsaXDo8w8WVDV7R2Wqw2ZVu1eJFP+VCNpqqX6kMv4z5SuNy3uvgZL169QheeBRQMwh84zWw
FaLXEHvz61eFHV7VCVi8fpZcciB07BGgRyE/UBiV0heQjlVxozIpBf9A15JzDkwllA4cQrz5CwW0bgee
Z9YlBA5wdAW/g2ONSfR8Bg73hHTwTDFD3oNAbwfRRD0XAH85KDl1XB3NzsusaPCAdt+ePP/Jzsx2pCmy
0dAZuSAbHLmrNl5yZ/Bqwh/ZhZLOgBDjFkSV6dpg4WHQiv3RseWUo+uD8bC3mqnkKO3IZy4OfrR+rTqy
+f/RXn1HuRa3OMrnKSNujhntCkYY5ZhjtEA45uTZLHu8YXtD7RALSX+y/YCPDbmQqgNlD5zTIFBr0w5L
kDXt4N3U24Z2mLgrjXrTDoJOtWmHrF+gsnhu0wo6taaVJak2rBdTbTOQhXSDSMW9m4HVdXbcwFrOHWQe
xWgcrBtrvNgH6/1xAcnQg5HFdZuZSl/azByiST3LgE2zlopXQLFDkwhmaxJp8b4mMYdYtNoknge7LHrB
aiNqj8MmSe4Hi/cmKWUL2yZla2qbbE1tk713F5M1Q9Z7Li2zhXeeJmdbwknt+dTk0NkbssnhrsEcwvII
bvLM6sROV8tXTY6FRRpYF5ntUbgwu1oTtl41t5Ymi9438q7U+DfyE9myN3QNMfICbxZ8b/yJbu5tsDiG
o74NjhX3fxtkmssiOdlRMpXn1JsELJQrbPWm5Hw0H39TCrFkrTcr8m+a6XO9eru6UCFq43r1R7C3yh/z
QNN69UeiYb16xxMrgMJHqicT950dbP7OeEG9s5bm+p01YP+7axMqDlBXfsD7kn+BauloP6ik7A/Skzn3
BxXzfqAhFwNxuHcAHzBzJIDPEukfdFvU/HGvqR/MM97H9ocEpr4Q9K4YOXQLuD9MMCl6AbLz/hcAAP//
w5+e+jUSAAA=
`,
	},

	"/data/en/top_level_domains": {
		name:    "top_level_domains",
		local:   "data/en/top_level_domains",
		size:    45,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/wTASwqAAAiE4f3Af8geJkI6ENWi0/et9aHNjWoOo1k60MSNfCVKvyj2B3WdfwAAAP//
vqoHMS0AAAA=
`,
	},

	"/data/en/weekdays": {
		name:    "weekdays",
		local:   "data/en/weekdays",
		size:    64,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/wouzUtJrOTl8s2H0CGlqcVgRnhqSh6UGZJRWgRhuRVlgungxJLSIjALEAAA//+vxy2/
QAAAAA==
`,
	},

	"/data/en/weekdays_short": {
		name:    "weekdays_short",
		local:   "data/en/weekdays_short",
		size:    35,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/wouzePl8s3P4+UKKU3l5QpPTeHlCsko5eVyK8rk5QpOLOHlAgQAAP//Ckj1iSMAAAA=
`,
	},

	"/data/en/words": {
		name:    "words",
		local:   "data/en/words",
		size:    1934,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1xVW45rIQz7R2KRKaRTS7zKo5rlXzlw2un9mjk0IY5jB0mQ4V2oZehzyVzdO1nTu6b9
rl1LxPBuYHr3qmm1KVOzdxLCGlImVvYu1lS75udS76Rph2TvVOwbbYh3zyX87eYdUqreoby0zNrVu5d2
TJmsotMiB7yTHh6YGmb17qYymf6C/YkIU7wbq0zv9LclBLlV72Q07eVPBzUStf17Xz/8f2hkBci74VUs
PstPwdUIkdRhgd51mahFv7tnJrwrOgIMRlFr9hBhXZOYXcpOD4eS2aQVD1M31oiGEUAq0n8oSy3elZWf
yyjFGt7lGuHd1NxqF1IZEA0EG01yM1ZZZaPZzTFdEvY9nEaX/ybKbC1gXPQuoyALIRXsFA6o1DE7G9Nf
7cHGVoslp8SoUHur3SI11+s+SiB/F9vdnZNLX2ONgIarC1RLK6AeiM7wI7I65cVyeZPxpd4NVZYVemny
TgkZi1x0bV0fWiJVd0aMsq97A3xPQsdQo8twPJDIftIxIYdjrEGJ1ohKZf4UjIFM9cQVkNclo1uSEjFB
aK2LDj3eSbLi5aNZJyuZgi4w5i9NWjBpi2k6C7X31XjwXFbrrdvjoA9OHv4GbXN1kGcKpYYgGoT5YTVE
7KZNbK3XF6KWS4dnFYyGgO3SVaJ6V3PhB4ZlymSn2vsWegZHpZdJSXBYqckho97vvI2NDe0WkmtKmDyT
gsyhcM7j0oJp7pI0P+7rR/bRQ/qxWlQjb/8uAcl2Cu/QvSmUnXJMY6KEyZGZMRJu2uvlKfLLK0ZNa5oH
b5+LEn64Er2rzfLD2mvvqAPZithcvGu181oK8hh4XJrLKGQM5vRKw8kvsnrXkgSlN+8SlFhapaIYfCj/
uEbGWFlLlHPzCTj7pmvTlLRE5u7WcFsfazwXP6Mcam1PfhnJvIOUDr1/1pueEUCuVj+gCneBd006zi6e
tuTr2apWy16P3ZRpwWDrDfNY9z3HokHHsE1j2Idoo/W4l/TsPP27yYY1viKkRJp0K17nl3NN6V3tCbMo
zP1a6RbTKf5AIHPl7GlWb9BCxdOSwUS/5hsxAs57ecHZoLNg29MIPEPga3WO96TI078AAAD//wYIBR6O
BwAA
`,
	},

	"/data/en/zips_format": {
		name:    "zips_format",
		local:   "data/en/zips_format",
		size:    9,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1KGAF4uQAAAAP//CqF3DgkAAAA=
`,
	},

	"/data/fr/female_first_names": {
		name:    "female_first_names",
		local:   "data/fr/female_first_names",
		size:    1242,
		modtime: 1606029860,
		compressed: `
H4sIAAAAAAAC/1SUT27jOgzG9wZ8qDR5/YekLV4GWcyOtYmYGJlKaalo5gY9yUSrHkIXG5C0286m309f
JIqkqa76WgLUjx7bZtXXSzAVQmalI6TBlOtlapsVjbXoOuAbsG5TprdvDjib3+nPYy3B9jHUj8l0SjC5
1YvH89s45l8qKRJjSmoJQ7bcpiTUt80q94JnVVniZomCbXOFwtD7sSuhIxmt4ZQ7YiOJYaY0oDjW0lFw
CIsTiKFt1gNwgmAgIXq0QWhKGMInE/AXGwYgcc397NQyImsz1jF4guvIU4LZE7LyN8DkoTfINKl69E2U
mAZrVH3vKQ2qoZbIVnh9DzTBM86+nazvIfZkMJK16b9xBM4e/1qA659oO6+llr4WoZeMbXMDzzIncYOM
r1Qvr9g2t7WEetFcbpGFvIbbKAlZY9z5dNxpFnb2HrqXjN7QewT+VHfiVMtpWNij3WdL08SMLWCipPO0
hSw4i7VsG0XAjm9jtiq2ufO/5HJumx30GNB27YAjq0jn+e1AjpDfFugdYmqbm3yeK1Uno1DCr19tu6DR
8ah39UCTXSbkZSrNMi/tBakuxnkyTQMFHe0ddYM/PKU5wS+K7J/mAdIA1iOlf9bURd36EGsZqW0eu1ps
cB7n5/AY6FU3PkES6rSlT5DnSVSyxJ5q4VpCPCkPFOh0Mv9/ZBu9PTzbek9jNI2nQYPuk35Mnd222efJ
u7DPvxeYgL+vz8FS+THUIvWinThAQPbmHCDoKCrVIkvlB+pStEd1IDmS3fQz1qIveSR/jMH/TWziSPOp
vwEAAP//H/waTNoEAAA=
`,
	},

	"/data/fr/female_last_names": {
		name:    "female_last_names",
		local:   "data/fr/female_last_names",
		size:    3360,
		modtime: 1606031711,
		compressed: `
H4sIAAAAAAAC/0RX21LzSA6+d5XfgVeJk8EsGzOphGKuFVvE/W+7FWS3C/P0W5/UYa5CuQ9SS99BdKRL
SHXVsCbSoa7eR5lorquzXFmXujrxEpa6OuSrBHwO/Wj7WtI+EBaU0lBXnShTrqsjf/J1Va6rS5gk1dWR
snJa6qoL/cgRO1S2uvLI/FNXB1rDUFfPkhYKifHh6RLiSn5rxFLWFFgR7i64rGFdPPCRJs/0LHmeLYc2
qOV4lvxdVx8h9ZYAUrPMGtlw11HuCN9ISrzU1S4NWHxWSr29tWPtLWiXY8Rvm1lRrCPfPPaFUj/ijpZK
fvuRV4r25zMejgIqduwjT5bFMyqdBoscKfVWatzaiV3eUl5GuwAng5L9YUv+wlhXL5x0QzFWin7CDryF
XiKa19E8o/YdaeC6ehMrImu578gTBeTWEUJltHUNjC8HTvZ00n60J55l0HDL1qc8We1PtKFex9wj1iF/
SkZnZH66UFpkrqtXiVt5nqOl4+z1eVw319WeFDm27M161GWuq0azdaRj61NDerXDQA46embHaiupp7ji
SEshRvuIw4iz1dUp9L4vKGV7yw3XXPpxCstSV3uJKOtOky1/hMHKKemHIh585EkMkGfpR66rXXak/R2t
XNjQR9b+C6FQ3bo6jSGG+91AlvXGThr2AA75+fccEIW088TAca8Svm1RpgU3cBJw75muuHpPeufknf6g
eeZsGM6I8FIye2VK1iincIzWw1YlDQYg3rAXtW1l8p7e7QJLRJxYVqROshXnRUjBqa7U/MBzP9J0n+vq
OXIGDHcDTfbefjTYSlBLEhzFFfuRNKJJu3w12NLTXuaFrEuF1NkU4dHDEymSahwh4KmluCHBPVmhX6n/
sodYceMCUujKHu23Tv+NbBlInv03RoMu2xvP4cpBxY7+chJJbAaSxGHwLj+1FGNdnXMAKijdovW1kew4
QDHnujoprzKjDTkGNqG4Ghob5aVgfSLjevBEGsmRkifD02axXLUOlAJY25F+GV2sOmLJX103kJd8flqd
itKob1j5K7PjbTMcOQklOQlfyJT5xEjCvuycRX8tgVPiB/8jmpmjZfzO81wwP1FYEK/NDzNo+KE3/iyA
piixf/iHrzj7Sr1cvQ0ODIhlfIidowY2YWzZk/rSgSPlRJv1Nq9G2cjf5HrdkbLnukuL0/XIV7Fu61BS
/sM58QOjJmHzVy5rN4VkIchiz3rJxVAO/ASmu2Y2Gh52s5mpWUJtiA+bVHVkzXRDbbD6dssbYPBGKylw
1vDsrTiFfkSKL+zH9zJi40lcHa4FLxfKq1134KeL5BleEJJVdlcCOw9mW1jEsLCMHA1M71nvZu7h5riI
wQ2wZdEbmzJtLk1/x4emATQA3oeE2c1uyA+lwgs/0GM2TkWrMk3ZHcNhEr69YIXiHUE5D2Eo9kilzS1l
k6RG7Mf1B4hRvomZU2t9cRMxruTgKGuipAEpnihH3P3HGAObQPtIB+uQQeGv1d3lSHfRxaR8ngMcqijm
mW9OindKt2wtndjGkl0RowOvhPs70ZWsICtELEBi95J1MS04QqyL6I1sRD3R3AOXH6ZrcE680sO+j+Hq
soURJwlEcKQJr9r/6+GALOUBommeiMZ/cEH1gaMonKOJ/1bQTX/z8kMTNLskdeRaHZ3OHxShkTgngz3z
VWa+jyWQC08Q6+i3hbvwLZuHUIEMDG4Q/zJJGsokhRyNp1yihp5dcZ2vRwk+pWEeMUq9Y6yhgAK9s3vI
Uaar940/xQmSl1xsRfLs0n8I9AMVB272bqj/cJjnuvpPofArcjRL5EgjbVwkyR3P9zR8y+zG5r524Gj+
eeK4PIZOLc6y/HKk8PBI6sMBbDstXITaRcYH3yNdAcyT+OGGflDHN9HJnn+SxRfeRRWZHelGOlhj5cFw
5+/0UPBW+TFPecFQeqdTtq4+h9kXupzkp67eeGXLtpcJyXTsoxbqkhKGpV02G/qHbsmmV8le5I7QvzNN
YOOJTDbsn4I/Nmt4q62fvwMA+2CXN/spnuDDK3qsJDaFc5mZP+jhygsXN4CzmpEUSowKo8K7KJQRPkdI
7DtGZQD7QpOJw5EHU4MLRTO5VjAyu5D1YpOaF5kjCtJw/z9rcaAYxWb+yE6PBc38fwAAAP//bMb/aSAN
AAA=
`,
	},

	"/data/fr/female_patronymics": {
		name:    "female_patronymics",
		local:   "data/fr/female_patronymics",
		size:    3360,
		modtime: 1606031166,
		compressed: `
H4sIAAAAAAAC/0RX21LzSA6+d5XfgVeJk8EsGzOphGKuFVvE/W+7FWS3C/P0W5/UYa5CuQ9SS99BdKRL
SHXVsCbSoa7eR5lorquzXFmXujrxEpa6OuSrBHwO/Wj7WtI+EBaU0lBXnShTrqsjf/J1Va6rS5gk1dWR
snJa6qoL/cgRO1S2uvLI/FNXB1rDUFfPkhYKifHh6RLiSn5rxFLWFFgR7i64rGFdPPCRJs/0LHmeLYc2
qOV4lvxdVx8h9ZYAUrPMGtlw11HuCN9ISrzU1S4NWHxWSr29tWPtLWiXY8Rvm1lRrCPfPPaFUj/ijpZK
fvuRV4r25zMejgIqduwjT5bFMyqdBoscKfVWatzaiV3eUl5GuwAng5L9YUv+wlhXL5x0QzFWin7CDryF
XiKa19E8o/YdaeC6ehMrImu578gTBeTWEUJltHUNjC8HTvZ00n60J55l0HDL1qc8We1PtKFex9wj1iF/
SkZnZH66UFpkrqtXiVt5nqOl4+z1eVw319WeFDm27M161GWuq0azdaRj61NDerXDQA46embHaiupp7ji
SEshRvuIw4iz1dUp9L4vKGV7yw3XXPpxCstSV3uJKOtOky1/hMHKKemHIh585EkMkGfpR66rXXak/R2t
XNjQR9b+C6FQ3bo6jSGG+91AlvXGThr2AA75+fccEIW088TAca8Svm1RpgU3cBJw75muuHpPeufknf6g
eeZsGM6I8FIye2VK1iincIzWw1YlDQYg3rAXtW1l8p7e7QJLRJxYVqROshXnRUjBqa7U/MBzP9J0n+vq
OXIGDHcDTfbefjTYSlBLEhzFFfuRNKJJu3w12NLTXuaFrEuF1NkU4dHDEymSahwh4KmluCHBPVmhX6n/
sodYceMCUujKHu23Tv+NbBlInv03RoMu2xvP4cpBxY7+chJJbAaSxGHwLj+1FGNdnXMAKijdovW1kew4
QDHnujoprzKjDTkGNqG4Ghob5aVgfSLjevBEGsmRkifD02axXLUOlAJY25F+GV2sOmLJX103kJd8flqd
itKob1j5K7PjbTMcOQklOQlfyJT5xEjCvuycRX8tgVPiB/8jmpmjZfzO81wwP1FYEK/NDzNo+KE3/iyA
piixf/iHrzj7Sr1cvQ0ODIhlfIidowY2YWzZk/rSgSPlRJv1Nq9G2cjf5HrdkbLnukuL0/XIV7Fu61BS
/sM58QOjJmHzVy5rN4VkIchiz3rJxVAO/ASmu2Y2Gh52s5mpWUJtiA+bVHVkzXRDbbD6dssbYPBGKylw
1vDsrTiFfkSKL+zH9zJi40lcHa4FLxfKq1134KeL5BleEJJVdlcCOw9mW1jEsLCMHA1M71nvZu7h5riI
wQ2wZdEbmzJtLk1/x4emATQA3oeE2c1uyA+lwgs/0GM2TkWrMk3ZHcNhEr69YIXiHUE5D2Eo9kilzS1l
k6RG7Mf1B4hRvomZU2t9cRMxruTgKGuipAEpnihH3P3HGAObQPtIB+uQQeGv1d3lSHfRxaR8ngMcqijm
mW9OindKt2wtndjGkl0RowOvhPs70ZWsICtELEBi95J1MS04QqyL6I1sRD3R3AOXH6ZrcE680sO+j+Hq
soURJwlEcKQJr9r/6+GALOUBommeiMZ/cEH1gaMonKOJ/1bQTX/z8kMTNLskdeRaHZ3OHxShkTgngz3z
VWa+jyWQC08Q6+i3hbvwLZuHUIEMDG4Q/zJJGsokhRyNp1yihp5dcZ2vRwk+pWEeMUq9Y6yhgAK9s3vI
Uaar940/xQmSl1xsRfLs0n8I9AMVB272bqj/cJjnuvpPofArcjRL5EgjbVwkyR3P9zR8y+zG5r524Gj+
eeK4PIZOLc6y/HKk8PBI6sMBbDstXITaRcYH3yNdAcyT+OGGflDHN9HJnn+SxRfeRRWZHelGOlhj5cFw
5+/0UPBW+TFPecFQeqdTtq4+h9kXupzkp67eeGXLtpcJyXTsoxbqkhKGpV02G/qHbsmmV8le5I7QvzNN
YOOJTDbsn4I/Nmt4q62fvwMA+2CXN/spnuDDK3qsJDaFc5mZP+jhygsXN4CzmpEUSowKo8K7KJQRPkdI
7DtGZQD7QpOJw5EHU4MLRTO5VjAyu5D1YpOaF5kjCtJw/z9rcaAYxWb+yE6PBc38fwAAAP//bMb/aSAN
AAA=
`,
	},

	"/data/fr/male_first_names": {
		name:    "male_first_names",
		local:   "data/fr/male_first_names",
		size:    775,
		modtime: 1606029860,
		compressed: `
H4sIAAAAAAAC/zSSXW4UMQzH3yPlUAstU0a7ZTWt+HrzZszEkMSDJ6m6R+hJIEKCF26QiyFn2ZfxLx92
7P9/drMQJmt2FFu1ZheAdBXwGdIsqPhFcNa4ek6b7qRZ+t2UmZJuSPZFrNmVpWwZr6CFXmH6CvE/cfud
FSSBzB2yQJqtee1BAm4KQlvm1aM1N5AIg8Ynmq25wUSbNe1l5tLTD/BMEa3Zc/vj9CBSQGtuY4RUNLG9
CPWDTJi0z9uytJ8KbwRS+8FaT9F909jq3GrPGOAk/ekBWRbta2hV+qMDhRNK7tA7HqTVhUmVGgqFACV2
PFvzgUIgiNbcYRKy5o4Td+HuylI09+0G4KwZwX3v6xEhWTO2Ku2vVhl5w9VbM5b+1FhCt2oPRTBla/at
sq656CT74voHNtVG3OWrYxxAuhkHyNkTFqUi5NCaAzmvV+7JcdDMe26/gjXvAj0RijVHyEIq0BFKsObo
KdC6ojVHQtGpJzhHVhOnVuPZmgmTzjiR812xiS+CTbxovYlDt/yh1RNsuQ/0kFtdPagzj75VnlmuuPpu
6qOnE5R8hXAhFDkrcNTOHyly9q3qdf2LVMv35DKLxuS6ZB/hMtanJ1X0M2iThNb8CwAA//+5tlQdBwMA
AA==
`,
	},

	"/data/fr/male_last_names": {
		name:    "male_last_names",
		local:   "data/fr/male_last_names",
		size:    3360,
		modtime: 1606031711,
		compressed: `
H4sIAAAAAAAC/0RX21LzSA6+d5XfgVeJk8EsGzOphGKuFVvE/W+7FWS3C/P0W5/UYa5CuQ9SS99BdKRL
SHXVsCbSoa7eR5lorquzXFmXujrxEpa6OuSrBHwO/Wj7WtI+EBaU0lBXnShTrqsjf/J1Va6rS5gk1dWR
snJa6qoL/cgRO1S2uvLI/FNXB1rDUFfPkhYKifHh6RLiSn5rxFLWFFgR7i64rGFdPPCRJs/0LHmeLYc2
qOV4lvxdVx8h9ZYAUrPMGtlw11HuCN9ISrzU1S4NWHxWSr29tWPtLWiXY8Rvm1lRrCPfPPaFUj/ijpZK
fvuRV4r25zMejgIqduwjT5bFMyqdBoscKfVWatzaiV3eUl5GuwAng5L9YUv+wlhXL5x0QzFWin7CDryF
XiKa19E8o/YdaeC6ehMrImu578gTBeTWEUJltHUNjC8HTvZ00n60J55l0HDL1qc8We1PtKFex9wj1iF/
SkZnZH66UFpkrqtXiVt5nqOl4+z1eVw319WeFDm27M161GWuq0azdaRj61NDerXDQA46embHaiupp7ji
SEshRvuIw4iz1dUp9L4vKGV7yw3XXPpxCstSV3uJKOtOky1/hMHKKemHIh585EkMkGfpR66rXXak/R2t
XNjQR9b+C6FQ3bo6jSGG+91AlvXGThr2AA75+fccEIW088TAca8Svm1RpgU3cBJw75muuHpPeufknf6g
eeZsGM6I8FIye2VK1iincIzWw1YlDQYg3rAXtW1l8p7e7QJLRJxYVqROshXnRUjBqa7U/MBzP9J0n+vq
OXIGDHcDTfbefjTYSlBLEhzFFfuRNKJJu3w12NLTXuaFrEuF1NkU4dHDEymSahwh4KmluCHBPVmhX6n/
sodYceMCUujKHu23Tv+NbBlInv03RoMu2xvP4cpBxY7+chJJbAaSxGHwLj+1FGNdnXMAKijdovW1kew4
QDHnujoprzKjDTkGNqG4Ghob5aVgfSLjevBEGsmRkifD02axXLUOlAJY25F+GV2sOmLJX103kJd8flqd
itKob1j5K7PjbTMcOQklOQlfyJT5xEjCvuycRX8tgVPiB/8jmpmjZfzO81wwP1FYEK/NDzNo+KE3/iyA
piixf/iHrzj7Sr1cvQ0ODIhlfIidowY2YWzZk/rSgSPlRJv1Nq9G2cjf5HrdkbLnukuL0/XIV7Fu61BS
/sM58QOjJmHzVy5rN4VkIchiz3rJxVAO/ASmu2Y2Gh52s5mpWUJtiA+bVHVkzXRDbbD6dssbYPBGKylw
1vDsrTiFfkSKL+zH9zJi40lcHa4FLxfKq1134KeL5BleEJJVdlcCOw9mW1jEsLCMHA1M71nvZu7h5riI
wQ2wZdEbmzJtLk1/x4emATQA3oeE2c1uyA+lwgs/0GM2TkWrMk3ZHcNhEr69YIXiHUE5D2Eo9kilzS1l
k6RG7Mf1B4hRvomZU2t9cRMxruTgKGuipAEpnihH3P3HGAObQPtIB+uQQeGv1d3lSHfRxaR8ngMcqijm
mW9OindKt2wtndjGkl0RowOvhPs70ZWsICtELEBi95J1MS04QqyL6I1sRD3R3AOXH6ZrcE680sO+j+Hq
soURJwlEcKQJr9r/6+GALOUBommeiMZ/cEH1gaMonKOJ/1bQTX/z8kMTNLskdeRaHZ3OHxShkTgngz3z
VWa+jyWQC08Q6+i3hbvwLZuHUIEMDG4Q/zJJGsokhRyNp1yihp5dcZ2vRwk+pWEeMUq9Y6yhgAK9s3vI
Uaar940/xQmSl1xsRfLs0n8I9AMVB272bqj/cJjnuvpPofArcjRL5EgjbVwkyR3P9zR8y+zG5r524Gj+
eeK4PIZOLc6y/HKk8PBI6sMBbDstXITaRcYH3yNdAcyT+OGGflDHN9HJnn+SxRfeRRWZHelGOlhj5cFw
5+/0UPBW+TFPecFQeqdTtq4+h9kXupzkp67eeGXLtpcJyXTsoxbqkhKGpV02G/qHbsmmV8le5I7QvzNN
YOOJTDbsn4I/Nmt4q62fvwMA+2CXN/spnuDDK3qsJDaFc5mZP+jhygsXN4CzmpEUSowKo8K7KJQRPkdI
7DtGZQD7QpOJw5EHU4MLRTO5VjAyu5D1YpOaF5kjCtJw/z9rcaAYxWb+yE6PBc38fwAAAP//bMb/aSAN
AAA=
`,
	},

	"/data/fr/male_patronymics": {
		name:    "male_patronymics",
		local:   "data/fr/male_patronymics",
		size:    3360,
		modtime: 1606031166,
		compressed: `
H4sIAAAAAAAC/0RX21LzSA6+d5XfgVeJk8EsGzOphGKuFVvE/W+7FWS3C/P0W5/UYa5CuQ9SS99BdKRL
SHXVsCbSoa7eR5lorquzXFmXujrxEpa6OuSrBHwO/Wj7WtI+EBaU0lBXnShTrqsjf/J1Va6rS5gk1dWR
snJa6qoL/cgRO1S2uvLI/FNXB1rDUFfPkhYKifHh6RLiSn5rxFLWFFgR7i64rGFdPPCRJs/0LHmeLYc2
qOV4lvxdVx8h9ZYAUrPMGtlw11HuCN9ISrzU1S4NWHxWSr29tWPtLWiXY8Rvm1lRrCPfPPaFUj/ijpZK
fvuRV4r25zMejgIqduwjT5bFMyqdBoscKfVWatzaiV3eUl5GuwAng5L9YUv+wlhXL5x0QzFWin7CDryF
XiKa19E8o/YdaeC6ehMrImu578gTBeTWEUJltHUNjC8HTvZ00n60J55l0HDL1qc8We1PtKFex9wj1iF/
SkZnZH66UFpkrqtXiVt5nqOl4+z1eVw319WeFDm27M161GWuq0azdaRj61NDerXDQA46embHaiupp7ji
SEshRvuIw4iz1dUp9L4vKGV7yw3XXPpxCstSV3uJKOtOky1/hMHKKemHIh585EkMkGfpR66rXXak/R2t
XNjQR9b+C6FQ3bo6jSGG+91AlvXGThr2AA75+fccEIW088TAca8Svm1RpgU3cBJw75muuHpPeufknf6g
eeZsGM6I8FIye2VK1iincIzWw1YlDQYg3rAXtW1l8p7e7QJLRJxYVqROshXnRUjBqa7U/MBzP9J0n+vq
OXIGDHcDTfbefjTYSlBLEhzFFfuRNKJJu3w12NLTXuaFrEuF1NkU4dHDEymSahwh4KmluCHBPVmhX6n/
sodYceMCUujKHu23Tv+NbBlInv03RoMu2xvP4cpBxY7+chJJbAaSxGHwLj+1FGNdnXMAKijdovW1kew4
QDHnujoprzKjDTkGNqG4Ghob5aVgfSLjevBEGsmRkifD02axXLUOlAJY25F+GV2sOmLJX103kJd8flqd
itKob1j5K7PjbTMcOQklOQlfyJT5xEjCvuycRX8tgVPiB/8jmpmjZfzO81wwP1FYEK/NDzNo+KE3/iyA
piixf/iHrzj7Sr1cvQ0ODIhlfIidowY2YWzZk/rSgSPlRJv1Nq9G2cjf5HrdkbLnukuL0/XIV7Fu61BS
/sM58QOjJmHzVy5rN4VkIchiz3rJxVAO/ASmu2Y2Gh52s5mpWUJtiA+bVHVkzXRDbbD6dssbYPBGKylw
1vDsrTiFfkSKL+zH9zJi40lcHa4FLxfKq1134KeL5BleEJJVdlcCOw9mW1jEsLCMHA1M71nvZu7h5riI
wQ2wZdEbmzJtLk1/x4emATQA3oeE2c1uyA+lwgs/0GM2TkWrMk3ZHcNhEr69YIXiHUE5D2Eo9kilzS1l
k6RG7Mf1B4hRvomZU2t9cRMxruTgKGuipAEpnihH3P3HGAObQPtIB+uQQeGv1d3lSHfRxaR8ngMcqijm
mW9OindKt2wtndjGkl0RowOvhPs70ZWsICtELEBi95J1MS04QqyL6I1sRD3R3AOXH6ZrcE680sO+j+Hq
soURJwlEcKQJr9r/6+GALOUBommeiMZ/cEH1gaMonKOJ/1bQTX/z8kMTNLskdeRaHZ3OHxShkTgngz3z
VWa+jyWQC08Q6+i3hbvwLZuHUIEMDG4Q/zJJGsokhRyNp1yihp5dcZ2vRwk+pWEeMUq9Y6yhgAK9s3vI
Uaar940/xQmSl1xsRfLs0n8I9AMVB272bqj/cJjnuvpPofArcjRL5EgjbVwkyR3P9zR8y+zG5r524Gj+
eeK4PIZOLc6y/HKk8PBI6sMBbDstXITaRcYH3yNdAcyT+OGGflDHN9HJnn+SxRfeRRWZHelGOlhj5cFw
5+/0UPBW+TFPecFQeqdTtq4+h9kXupzkp67eeGXLtpcJyXTsoxbqkhKGpV02G/qHbsmmV8le5I7QvzNN
YOOJTDbsn4I/Nmt4q62fvwMA+2CXN/spnuDDK3qsJDaFc5mZP+jhygsXN4CzmpEUSowKo8K7KJQRPkdI
7DtGZQD7QpOJw5EHU4MLRTO5VjAyu5D1YpOaF5kjCtJw/z9rcaAYxWb+yE6PBc38fwAAAP//bMb/aSAN
AAA=
`,
	},

	"/data/fr/states": {
		name:    "states",
		local:   "data/fr/states",
		size:    487,
		modtime: 1606031350,
		compressed: `
H4sIAAAAAAAC/1SQP67bMAzGdwG6w9s66RCOgdcOSWCkQ2fCYmMCMplHSQHcQ/QahfbeQBcraDfDm/Th
4x/9Pg4pw4zeDR+VChCbrE/Uu6mTVL3LIRUL7GpELmrvAuvDrDBoRN5Lohm9e1fgecEwylp6867/Thgi
ht1H787A94pR5nCTmjOlJOzdmVapmUyJ6oFyoUhh2rQ37g2zd1fRGCbItm6EBJS9O0HOGK6iK3Ak9O4b
1PLJmGDbJ85CRj7RDHoUhIrUMC6gyMU+mFSexDOGIT0wh7H/LfgWvwy/qnp3W4T/V7z7WiFikvowTtBC
TB8Vzd/A2G+9VSZL9h2IS5gIVTFgCRdr3DNfYJNS8NVyAi1Lb6m3dXt5x2rvfkBKlG38vZbKYPBp494y
4dtPBe5/gOz6V6lPTGm/T29R2IL+CwAA///dVKDa5wEAAA==
`,
	},

	"/data/ru/characters": {
		name:    "characters",
		local:   "data/ru/characters",
		size:    162,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/wTAVXEDAAAE0f+dWS9lcFfmJhMnYQYLd47yMpZMJFPJTDKXLKQjyVKykqwlG8lWspPs
JQfJUXKSPkmfpS/SV+mb9F36If2Ufkm/pT/SX+mf9F86kA7lQi7lSq7lRm7lTu7lQR7lHAAA//8HWqsv
ogAAAA==
`,
	},

	"/data/ru/cities": {
		name:    "cities",
		local:   "data/ru/cities",
		size:    2406,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/2xWbW7bSAz9b8B38AV8R1lq0yxs1E03QbtqascJFvm1W9my7Im+coXHGy34SI3lYv/x
YzQkHx85whcc0aCSZDrBF5VQywIFOhwlQY8D7R0KvKNQWRKcUaBFIQvT5SPPl6jQyEoWqKM94B39HBtZ
mIgDar9mIakkKOxjWU0nuEOFEyq54QWqNSjRM40jLSYfPMSdJLJG59pXFGhwRIE3avp1QI2Atxl+MvT4
st8OvDCfzyjNJQkqWVNuUOCIgAN6PYPeow32FoHgfUVv+aLUujyI2nqUmpfpTKDTSlWXJfa0Ma6scZaV
Qjud4E/WE+STyZLKJwRtBPWKrepwxEmLoM2LUwQvunxk6Wa7Z7ZpbOy9ZNj7nQ8Gj6xQRYQf8BalWnMg
MprFXjLP+oFI7CVD6fc0Hu0bCiIx3PFN80CHcNWI7ziQPpplT/00yuA7zoaQ63+hl1vmksyx0dDTCXIU
5KTRKDfgGKgbNYP2mKZpa5z1lOkkaevQ5KjQstwhsVy9ksjS5Q6V3HqzciUBAhq2+xAtF3lhHi3aS8kt
S0pK6svpHuerWcqdRq23Kjcq8guPz1FaqF/WM06aFtf95lR2FGTryCbriG5u7JRbSRU0SWnLov+HAa3T
YR1Cj4p2ne5hcn9I5qwLckO4HtkSRtLUyZiBk4/ocRqx5JEnamWFauRZy+a6n5YeLeUbZVT0LCVFkD8Q
XLvleCvEPxFwIiX+dxtcuZ9RoNRm0sGmWd4kyJDn4FHbXpvt9g3aQZJE7njLhpujYD7W5C0RcErMtFEz
bFATzS2n5Mz6t76LBswaWc11sDhkCwIVuPDsYMsJUNlGVWv8MFhY7ZnXXFi4tZsoKT36Ee/UUkdebr3h
JmcjcEeaZ1TNfJss6V5rX9xiVz/FbXqYXe/ia+dcoZnjnrTM1CeZQ/PE5Rli+584zcMW2PkblfDsjium
lnQ+Aueyw3a+qYarBv1dMvbPdUuJ+oG32G6/VLXTudC54kmbQkvGmhHUP1Nc+cYeo+t9GBlaWs57NUqn
d3yKSK6d7wR9UIPp+kCoRISO3G8a3OisxWknS7e0ESnT9h79WUuVTPOjpoUmfq7nqQs/nl1bS6oNdkt7
8UqCkz+YqqXxcXtWYAeJy6ay6PJZt65n9oIyPoEvFskeCo/wIh94x9+sJZXlnJumu5rTV1RMm781zshX
rtf1FX1ebdL8L8V20z8Mz9mdTvDv8DrOORmOg3P2Fxo/9utqybEH/wUAAP//V2UQEWYJAAA=
`,
	},

	"/data/ru/colors": {
		name:    "colors",
		local:   "data/ru/colors",
		size:    230,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/0yOwapCIRRF54L/7Ltv0KBJEVTcIAqCpnbLsszzDev8USgXcbbXVvZZjOrw+kfWJW9r
OBPJxJo3CEn/uSGVdwQSof3dFtZhpmNZIvMkMM3dhVg2CDogrT0QSR3vyTyI3BFrOCG8utcVHyY8X7y6
YmcNI1KyLsjdtStBXbNbV7uafwEAAP//WduwtOYAAAA=
`,
	},

	"/data/ru/continents": {
		name:    "continents",
		local:   "data/ru/continents",
		size:    140,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/3TMsQ1CMRCD4f5J2YFRj4g+1zAAC6BTRCAKBFb4vRECpaChtP3JODe6Sto40ag0GZNQ
2eE8vrEziLRx5vpvcqr2yjKC+/pzHX7EkSrjyWv5qUzIGMp0Lp/2HQAA//8vVur7jAAAAA==
`,
	},

	"/data/ru/countries": {
		name:    "countries",
		local:   "data/ru/countries",
		size:    3203,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/2xW3XLaSBO9p4pH4R0lESeuMl/8+1UcMGtjeze+cSIEMgNC4hVOv8I+yVaf7hnEbq40
fSTN9M853YMrVJJLIRlKNAhyORz0sGhvUEuGJUpsscYHSrTEG2Jt+q7BB4JkXLdYoUOD0q01Osn0HLOl
QMBKxmZLhhVqR9uE7RWLu8snrPy0XAr34Rol0b1cuKXnNiixRi3nhrnv6kHuyJlkqLH1PWo09G4sueR+
nqEBm7iWCVa9d616yrVGueIp8W3HP6ujLXmKQ61CclT0VSO9ZvY3CKkC1+oLWvWQ1lgy7CwzI7yilBxd
fMEP1whux8Tc6FPTK4WMaVs4O3RY0tWiV7obBrRKIZhdSy5j+Z8X8UbDkAKdfEErF3TtRiaopVDHsB8O
cIsSS3T0QNd6SvD1NgWs1h5LP+u2h1fqL2rsSceIBfpyeWqNcK1MQMnwbsnQfS+kW3UDa+auZN1vWfOW
TCijLZ/j90zlxq273k53ymosmdxAu8Oebmg6y/8iaCXXJ//+v7IGB03TcIBvJ6F/Q6ClSatQDwe4x4Zs
CMo32iwuv7Z1R15sEtZJpvEkb+/5/y6tWl81/CbtJflvkMPJPkWvJ3xnUWruNrUij5QlPLx2cENhHcU5
9WA7axoJqY21bh8LMmX1SzaQaU/6U02go4GtIqQEGBI0iV6eKeZ44rNDI+Neuqcskwpdm8WT8hsHGWPp
yrBSaqAddqRNgSBf+F0sp+5+x/1////UVVKO8HQCFiOs/86+4x4VZclw+HPpq0r1TpbMUHqvmtGJ2Elm
PLJTEdLSsOsk2hl7jqV+1us/M8qw4jm6PqPEWjnn03rgTL5iJzmDX1Izq+EADyhRMb3afbZ95KR9PFgJ
2QUtVZmjO9TO2eOXyruKpYrWNpXTkPROJspPVCyYI3qyWZJpobSlRVvO+X+DLv1TM65YiQd0SlMjBVXy
wG69Np/ch46kjPt2aZb5e5nIJVrtNsMB5twtJJLNtSMpwbmuqamG66AzjplJ6/RP4LxKKqXvc/OaKo6T
cq6RORXn1L6yJs6lP3CFdz73zoNHxtGfmI+Wc/r36PKzSNQ6+DmP8Vwyakuk9qgeKayJ5tosyXTIcA7H
HD1RBnGWPumu7DWlW3u5SJxYeKUrn9GZYyrD0tftyAuuTbY7gs+UdG2AjMm1qifXBXe12aoNZU1MdXZu
M53fBt+BQ8/iiLbq9kZPpThayjO90OZTUKcJmsnXFPbCr03RCiQSk+xBhkSBhZHWy9VH6l6i3nDFZ8d3
e1IzUn1BJMpnwWRYyRcUdEhTesGpzcvYSHuKzZThAM+swIfpvceZZ5tIVkO3W+oouqZ1WLEwz64Xrdyz
HxvoCv9kn9N6j93ifc7WvOX073zE0oR+8fufsegFG+1+//L0xRp3ukW+cNQcWfzKflTH5o6KV5mab4LF
7uuGU/vA0l841qKh8uPMfLUJmzz80xVpg0ORv4wXdr+WCctVyifvqac3hR+eox/0r7WMJoIoepbWwcv8
5lPjc+/+SSz59Kb4iCOl9Sb4jt2J2Nzm3U4di66aW+/W7nlZMpu3wFSkd/mEgE5TRfsnrjgff+Ij3RN/
kZlbP/8XDsf//wkAAP//71b5YYMMAAA=
`,
	},

	"/data/ru/currencies": {
		name:    "currencies",
		local:   "data/ru/currencies",
		size:    4765,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/4xYUY7bRgz9N+A76AK5RhE0P0XRfrSnseVkd4HsxtsgQIG0KZIgKPoTVJY167FkSVd4
vFHBx7E1o5U2/UssDofke3zkLCp4WckrFDhl+Av3+LpcoJCX2KNAK2vU8Dhmw0/waoAGu9SggUPNsyuc
ZBt/qmSl/nmulRwejdwOn/ey0R9QwaE1I+zRXYwK2WaoUfLDAUW4ZK/m9GZXdXAZejhZo6OXUtaS8+pG
L4riUedo1AsND3CyYj5HVHhI8zrx2kLy5cJSxl6ParRyc4lPchT6Txqp9716T6tTmgd5JSs4HJMKaRYh
np1sZCUbtPx1CFteMpeWVd4FEzefl8XhUabJxz+rt868sQwpMAyzQBMSV/RPT1wmuawNpAG1XqENVXFo
0GnYso6ukA12eutyoWe0CKjmLlGMAzXgcJisjNygZFWuEgASk2tN9FKVEW9qeIIZFf4Nk7oNETSywQm7
+fOd8o4U9ZbTkA/PaxZqyNSn2SvXCbtQy4q5F8vFkEmGd3iAJ2FytmWlPJ08xSZ4YK9PkU7uGHMXYxef
dtjDM7w8LulGG5CnX8KjQx/RTF4TM4dS/TC4C5YZvsCz1TwTop+MIWgnNgxMcS4zfNLShFgdWmWsfmIt
GSFbi2dLxronqQ6Xyob+Ix76OUFE1uY8fIhxDTUqeHYdTMoQx0xbqkGhWVA2EpWrWbwr+5mmWtxA6TnG
m1GliqBBDOA0vKJXQEmKVyxGOcZ/E/ArWbq9VjcKnGc8a59leDthQ35cEdvWIkcrr01GjIPZ85+/Wy5Y
lYpWjqU/DsqoaGig2+WC4JXmwOPAwo0050bHiGoFi+QTFXzkjtmjntZR+9jGcuaDnHlZU8PboDWPemxL
/Gal1bNyVdrbcTtt0afN5FncQuv827l7/zUjePjs+x9+oXY4/v8Y18PzYnZEkKcVu/EQk7jjeK0DhTvr
rdjPiiE0cqshfPgWqnifesqyF89/XC7YLSV7tAv95yJsUF4EI/wrw0dKWm8yT0H06p1HiaGS1BQ7n8ax
5mjSsUlZjRHNz5T9f0nNxDJyn2Uvfv3JKo0+wx8oqOgm0ke95x0+LhdhiCbxDIp4owV/FkhWzzO44bTR
poikynPZaKgko+ndhE1kYrDHNTtR7hSj+hFJz+sezZTVle1K8apyNB+Mf2/yF19ls+2sqJVxW2V9ssJ/
cjVyQR8s75Pc6o5o29VQwOuQ3mmY9LE45LJReVfHIUAdLj6iBQu80f6wa84mT2FwTrRMTGzj1Iho4igz
8UAfzf2zl2Okf5fO01z2AVfN7XCZNXW8aTqus3VQqWRgfuAJzzOeSupNq9OgW8oWZwJNaqJUcMdONrOD
bSJcVLbnYao37sJZmycOD9MbgQp9H824aalnqi7R2gk57cY0GJS6DzvhKV5grbtVnAqaOF6c8HwYNBRH
ThMuKQ33mH7u1dCTqz6Rmkep9SNe4mCl1PvMh9Wc8nBMHzpF2Ba8KZstilOZRxno3Sd5PX5tHU2Q9eky
PYXWKGTDWpfJDbLVGyjmRw7cORBlzfNzGkd+zEzQdWB9oWqQbp0R9LKWW8K3QvGMSXXjLLlT0GEXeuyp
+agRh46bf61ocFHjjNKyRwwfQxS2KpHmwOW9Terlgjzxjxm+MyXjZxvG9WhemxqmSOeMvqbeTL9BqYEt
GTqJuXlwcjVsimFHTPXkc6iSJ76Vjmqf4bMJgCrvKDAqm42727my5ucX+jeWGNmQKsWlCRmoCXsZ+LMJ
f22onl6Hkpw+4R/c61lyOG6/0etKnwe7IOlnSLTHLpuyI4/u0i4fXs56mzJG7mSlS4ieI5HzKd5ZztGz
7T2+4D7D37jHW3zFJ9uX7AUm11r2Z0G4fdraKYd7wuyjZUeT5DWl4nlghU/hadSFP6BYYz+O5nfc4yve
MpojXxduUpLlDR7IjIJOxk9cWcmdwrZcRENueqqqWpDG6bgc/iLwXwAAAP//aX+ZbZ0SAAA=
`,
	},

	"/data/ru/female_first_names": {
		name:    "female_first_names",
		local:   "data/ru/female_first_names",
		size:    542,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/0yR3U7DMAyF7yftnbdeVzANKtBG+XsAFNoEonbtXuHzGyG7bthNVZ+c89lOONDLjsyV
K5mJsN1wYCQxyJ7ARJSdqxNB9lLplyz3rq2ZSSpmpkI5Eoyj+r+WnHYkM2hCuxvrwfyr85EgO6ntpKEj
MjO4s2EgSGWs1d8svcp/5pdAR9J5txuemC37fJM5MZonOvdks+xv5j3rFKp5lYv3LHd8M9NJ7VXkQlbi
dsPLknOKV5ZrCUQSP0Q7a22TwOi7tiX1Wl5gqUap6e3/zXj6CgOJzrVk2/Te551Q5v7wexgL7ZPAZaEs
lVTa30+/9P6U8hcAAP//SeGmIB4CAAA=
`,
	},

	"/data/ru/female_last_names": {
		name:    "female_last_names",
		local:   "data/ru/female_last_names",
		size:    1826,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/2xV0W7aQBB8r9R/NjZFlUAKhqRB1AklRWr61AN84mLj4xdm/6ja9fm8h/KUeG93b3Zm
bsEGJxh08Pz36xesYGgCh5YWsCG2g6WcspizxxWOMlVVwdE3GHygjbEDlajhkzqPBl7l/JPvE1p1l8ct
ni/RoaYMNp4vJbehyacxE/KH+p+wOMKijrlryuBwZlxqwj3lsLglTOxhcaVSRXYwgnX4LuFxRp1UvcCF
GU3s/ih85XLzEHvqMSjeuaaJ31sqcEEHS7O73o5yOHSRUcFDCypD1hscrvA0VQy9UqZwL2kqmA1NFAcH
Vh0ON8X/HpYynFWnZxhWWiGvYCjHSeWsBJ/HmTIY9oCeiRbMRsBfwYhugnjIgsdFod2IF4eKtSAydzWV
IGoUU/yfU5EqsH2JkV/wuCbavUrXm+6KJpn1mT1OszhpCYuWHkZ3sUNE51Z7mHJ4dc8TTRP07FLPWUqN
R+k0V+ytqRDXj+ddcs8WTs7b6IR9mLmJ7L3JO/Xh/Y66ZDRXnQafTROHbmWGWtjXSFnVmjJ6wClhhmsZ
0VD/gwqlxyr0Pirn/hVtj8K6V/uAGW6UJ424TW+od/FUTTnPyH3vGP7DSChP+pSibPri3Scb6yhvLE4r
VTfVxSrmKlGk7T0a+M5HnWmBk9qPWbILNzjLm0y47T2qEO2Cop6mKq+kuZpsiaNMNs6/FhYL2YUjr93Q
PSrA0aa/jSbim4/xfVFOc8XWVjzUzzvE3qlgXWgWfxWyxPmH3nvBjSveksohohwczeTVPUi+FUVy5U2D
S8LIb/qeOOYRll+G6ivOZf1Z7bA9733YRVQvMFSM3P0PAAD//6le6doiBwAA
`,
	},

	"/data/ru/female_patronymics": {
		name:    "female_patronymics",
		local:   "data/ru/female_patronymics",
		size:    248,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1SOQQoDIRAE74H8WSW5edinmOBAcKP5QvWPArLLOteip6bY2DGaIoVOVWDwplPuN7aD
GHYxBT358HO70+GWdCUGfV0q0hjsylRvUOaFKcyb5RuNQlV2DY9ZWxQ9nywdft+cML6X+R8AAP//urY3
xPgAAAA=
`,
	},

	"/data/ru/genders": {
		name:    "genders",
		local:   "data/ru/genders",
		size:    32,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/7ow52LzhW0XGy/surDvwk5ergvTLmy9sBfM3wHiAwIAAP//k0YA+SAAAAA=
`,
	},

	"/data/ru/languages": {
		name:    "languages",
		local:   "data/ru/languages",
		size:    442,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1yRy26DMBBF90j8M2Alq0h9rKI0VSraruM2WHUKDr9w7h9V40VjWM6Z4epczIGoDs9V
Lb9ErnXFXi0znlSwRxIXRpsK+kkkMRDtQg2er2J74qZGnRwXPKN2xe6JkBPX/E1ObTGfmbktTM58r9xe
8NowkPB1xSuBiaDt//5gHoSF+Ue2TdrK8VPwnsBoxnJ1xRFvd+q0yR17OUsqsns8E3HV4lk7gjozYir4
uxqGnLzPf92+elh0ORpdvceJoEYtkeFO/wIAAP//Y5R5OboBAAA=
`,
	},

	"/data/ru/male_first_names": {
		name:    "male_first_names",
		local:   "data/ru/male_first_names",
		size:    462,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/0yQz0r0MBTF94G8c1v4dgOf1hFE1HHAtYS2gcy0ja/wu28kOU2Lu5x7cu/5wwMzkbu1
BFYma7z7M4vchFeCdWRm0jGZrKn8I9kakrXe0RPKdsHieoK1pGOzJ3Evt6TUk6zTxs7OBCYSC0k/nois
RV/TW50UvXHH0ho3D5qctbP5OetSd3DPDIwbL/zCUJLrpRt20nu2k/33jlcyq7VyuVpH0t83gvpJLELJ
/hFKSu94Lwm3XAfKylX0PtTt6B0XAgNROxdi8egdn2SW6uiqHsfa8tU6Ij+V+yIy1Ra/93S/AQAA//9J
zDm8zgEAAA==
`,
	},

	"/data/ru/male_last_names": {
		name:    "male_last_names",
		local:   "data/ru/male_last_names",
		size:    1632,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/2xU727aMBD/XqnvHBKGJoFUAnRFLJTRIa37NBNi4SbEvMLv3mi6s3OYrR9tn8+/fz6s
UcOgh0f9+IAFDI3g0NEMVnZ2sJRTFs/3uMBRpvUVHH2BwQe6uHOgEg18csOjhdfzP7Kq0Wl/j2s8m6NH
QxlsPJtLVUujT3ZMrA03v8PiCIsm1i0pg8OJcSiTPeWwuCZs97C4UKnrHYwgC6sSHic0Sf0WLnIxsedK
9MjltbDzHF5VPbm6jasNFTijh6XJXUdHORz6qJa8TzMqpeINDhd4GqsGr5QpxjmNBZ+hkfI8sH9wuKqu
e1jKcNIOLzDsmqKsYChHrecLRsPsKYNhN2/oacaMBWsFI04IvlABj7NiW0uKQu1SEJi76koQtKoEp8Lp
uooqnsP68QE/4HFJ3HiVbtdbN7QJpxdOJU0ioxIWHT0N6WCfxbPuljzK4bX3M40TpJwuzxWq8Uo6TFWb
JRWS0uGsT3pv4OSsi47uI7M2avMmf8jHnzVondFUOwwpGSfJ2gjaRlS94WKPGsroCXXCnW8xhnDzGxWq
8iJ2PGrefotTR1HT6w9l7VpNk5Gs3GbEu2SioZzZcL879X7x25QnHUrxKf2H7r+ZcZSfEFlJ/VVvW1Wm
Ep07xhyVzAfPaIZaZ1KWTKA1TvJjEtVCsvT9XfTH01hrSpoq/jmOgn9guBSFCplAg2L90DPqyntteIFG
4v3H8Acop6lqsZEUBFZh550K1pomcd5mSU4PITeSowXPJXVZfICjib51kPnoVaEtDM4J65/0NXF9Bcsp
1n6SN/aRfQvz6p8M9RHHFoaKQZu/AQAA//9ny4FaYAYAAA==
`,
	},

	"/data/ru/male_patronymics": {
		name:    "male_patronymics",
		local:   "data/ru/male_patronymics",
		size:    1222,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/2yT3W7bMAyF7wfsnW0vQ24CbPMSINjSnxS9bavaFqBGsfMKh29U8NRtSCV3wkeKIo8O
8RsZEQepETBikAoTOiRZfv9mYhHR0BFBGkzIsiq43i9ymTnaqlLhgIDB35ZKGkQcTeYfTOgxsDNHpUKS
2rAWgb3qa8llzxGp3GstgtRIxQQtEg7ar1OhRZJGqxS5WWdAwhGpyJ8jUvPU2Zj8kiXilchf7V6VZc3o
uPbTe6oKoNeI62pNrRKyqbxmZa/Xml03rHK+vUGHniquHO0LRTay4NxnskVX/NJ2vhUNUQU/z5PqLwtz
4x911N6zoxNGqfkDl7/7X9XhxIOlsnLa7hDoYt/zji7unF93SPITAW+uhxv1hfodweTe0nG9ybvjn2ZH
IlW2JM/bY+e4x4RXurQp6LHQdc8diSWjQ+wk+w/Frrpwz007FZUfEKTiXlhGzWThaj8iqt5uLmWZ+1M7
mkhPOBn6hEF+8DX7a8+Fl1+oeUeVv5i+eTnRewAAAP//KlGO8sYEAAA=
`,
	},

	"/data/ru/months": {
		name:    "months",
		local:   "data/ru/months",
		size:    160,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1TNMQpCMRCE4T6QO8fYiqawsFBBsDdGtjASvcI/NxJXRV+33wzLcGLQqEpaxMARoylR
ubm33uQYKDyUsF/ONQY2WjI8eV3vrtC4aK6Z/x0whrJWnD8be/rEO+5/WmN06tfPAAAA//+ydSAYoAAA
AA==
`,
	},

	"/data/ru/phones_format": {
		name:    "phones_format",
		local:   "data/ru/phones_format",
		size:    28,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1LWVVaGYV1lZV4uJCYgAAD//3RKfFMcAAAA
`,
	},

	"/data/ru/states": {
		name:    "states",
		local:   "data/ru/states",
		size:    2845,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/4xW3U7bTBC9R+IdfPl9F7yj47QFKagOlKooQGiCEFctG8cG45/lFc68Qp+kmrNOAqoz
5gYF79nZmbNnziymyGWCNQpJDw8wRS0JHF4OD3AGJyeo4CWWBF5GXGl1RcYSSyoJSu66gGOEHeISLdYy
lhMUW9QMDis4iZGjRAt/pEegRsWPO1CNRiaodl8khpNjOBTIdNsDColR6YnvQAXq7f8eDcrDA1yH4HiJ
8As1P3im4JF14AWcfIaL/sMjKhmHhP/ngh6oZ7VwkkaYy2hTUPQnvoiUL624C7SEUwYkfsPEUibIGHwp
Y/2lge+QoyGJG3Lu4cjDpiAt8Rht+B02ysmmOPLx7rpkpHxpkZUu8v5+BL7xooFRy2kfSPlulFtJepd5
1EhvC3mozARJ2g+5JYtN7xKvp6HMepYXLDCTGB6v8PvquN+KyyPrA8yx0rvizZSkLlzAiLSnEfwOIKcK
kFhVoUJWYXXH7oHqrzjICO1+4BkluqYCPXIDqP1lRTqn8HIyV1plnCtneiTW5CIfgnqCbRjTb1HgaT/s
UjVL4WQGSPtYW24/JDiCGkZJUxkognAZW5nNUKChIM3cZkrsEMR3V+87cffDVGlY29qY2XK8QvFRCq5Q
4hWFfNkHuKZfq3zMjNQpddGk4Jq1NXakG5R4QvER5d/QmD8M1AxLrOwemFuXM+fgaLEKl2QDa5uMW0Z6
1r8GaJjUn924tUGS4tnmfaHuvrXtfRA618Bh3YwMnWjBwrzMh5haqOOjtplaMv2VHWkZjrQAZnPqWDbd
fSlf1S6sRO8YIR1yuwcOklTlakV7VOnLiA5vRPu26RG4SD6hQE7qOeqZyRo+wjPfLsfBPfho2LR1BtdJ
pEUlyRGHdMIYXS9sn0CuU2M3gDk+M35p+dBq+zP8zrlddM8TQqaY/7tbJih0dyWxjNWZ2N6acTAxjvKw
856CT2RyRBdr2f5vnj9TzMPL7Hfwye75pK/Y5B1KeaZt1fqi7D/tbwAAAP//vsLF+B0LAAA=
`,
	},

	"/data/ru/streets": {
		name:    "streets",
		local:   "data/ru/streets",
		size:    734,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/2SS3WrCQBCF7wXfOYmUFhSkP7QQa1Nv2l7JRl2NSbO+wjdvVHYS44TeBDJ7mPnOmeEL
TyuZJDgaWdDiZDmd8E6gIXDAcxyqP9SxbnQbAju8ZJJS97UVXtJBsVbFVe04mP81jhIvyWjKGy5W5N7Q
VJGw601LFV9U6Wm00ukKpfZD/5XM2Jt5H9SSyZJSElkY4pzAr6Tx2/kzb8849kp0nVoo8U7VjrPRbnR2
fB3ykQzPZZRXQztyl6s7pZxO2JokCiqCqhMz5bFPzDrbUlKp97NJPpIHQ5OruzsCp6H2RJBUMoIh+hzx
FTKTB+qbf6Vt4tZjLobstd9H7B5vJ6jyaPrGfcdJ/+5J5pz7DZZ4DjLXfZ1GaebxSpXjyvKN44Lrdj6d
8IK7kf8FAAD//3wrFA7eAgAA
`,
	},

	"/data/ru/weekdays": {
		name:    "weekdays",
		local:   "data/ru/weekdays",
		size:    124,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/zzMMQrCQBCF4X5g7rwZwSog5AIhla1RBySyc4b/3UiyheXP+3isFJ3kTfLVTOfD4cai
oNT+vakN9XDjTip4kmq83Fh1U5xS17FvurCzU4rRC6WJ43zQRNI1k26/AAAA//8RK5GhfAAAAA==
`,
	},

	"/data/ru/weekdays_short": {
		name:    "weekdays_short",
		local:   "data/ru/weekdays_short",
		size:    42,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/7ow/8JeXq4Lky428XJdWHixgZfrwnIwez5E5MJGsGwjLxcgAAD///WooMkqAAAA
`,
	},

	"/data/ru/zips_format": {
		name:    "zips_format",
		local:   "data/ru/zips_format",
		size:    9,
		modtime: 1606029396,
		compressed: `
H4sIAAAAAAAC/1KGAF4uQAAAAP//CqF3DgkAAAA=
`,
	},

	"/data": {
		name:  "data",
		local: `data`,
		isDir: true,
	},

	"/data/en": {
		name:  "en",
		local: `data/en`,
		isDir: true,
	},

	"/data/fr": {
		name:  "fr",
		local: `data/fr`,
		isDir: true,
	},

	"/data/ru": {
		name:  "ru",
		local: `data/ru`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"data": {
		_escData["/data/en"],
		_escData["/data/fr"],
		_escData["/data/ru"],
	},

	"data/en": {
		_escData["/data/en/adjectives"],
		_escData["/data/en/characters"],
		_escData["/data/en/cities"],
		_escData["/data/en/colors"],
		_escData["/data/en/companies"],
		_escData["/data/en/continents"],
		_escData["/data/en/countries"],
		_escData["/data/en/currencies"],
		_escData["/data/en/currency_codes"],
		_escData["/data/en/domain_zones"],
		_escData["/data/en/female_first_names"],
		_escData["/data/en/female_last_names"],
		_escData["/data/en/female_name_prefixes"],
		_escData["/data/en/female_name_suffixes"],
		_escData["/data/en/female_patronymics"],
		_escData["/data/en/genders"],
		_escData["/data/en/industries"],
		_escData["/data/en/jobs"],
		_escData["/data/en/jobs_suffixes"],
		_escData["/data/en/languages"],
		_escData["/data/en/male_first_names"],
		_escData["/data/en/male_last_names"],
		_escData["/data/en/male_name_prefixes"],
		_escData["/data/en/male_name_suffixes"],
		_escData["/data/en/male_patronymics"],
		_escData["/data/en/months"],
		_escData["/data/en/months_short"],
		_escData["/data/en/nouns"],
		_escData["/data/en/phones_format"],
		_escData["/data/en/state_abbrevs"],
		_escData["/data/en/states"],
		_escData["/data/en/street_suffixes"],
		_escData["/data/en/streets"],
		_escData["/data/en/top_level_domains"],
		_escData["/data/en/weekdays"],
		_escData["/data/en/weekdays_short"],
		_escData["/data/en/words"],
		_escData["/data/en/zips_format"],
	},

	"data/fr": {
		_escData["/data/fr/female_first_names"],
		_escData["/data/fr/female_last_names"],
		_escData["/data/fr/female_patronymics"],
		_escData["/data/fr/male_first_names"],
		_escData["/data/fr/male_last_names"],
		_escData["/data/fr/male_patronymics"],
		_escData["/data/fr/states"],
	},

	"data/ru": {
		_escData["/data/ru/characters"],
		_escData["/data/ru/cities"],
		_escData["/data/ru/colors"],
		_escData["/data/ru/continents"],
		_escData["/data/ru/countries"],
		_escData["/data/ru/currencies"],
		_escData["/data/ru/female_first_names"],
		_escData["/data/ru/female_last_names"],
		_escData["/data/ru/female_patronymics"],
		_escData["/data/ru/genders"],
		_escData["/data/ru/languages"],
		_escData["/data/ru/male_first_names"],
		_escData["/data/ru/male_last_names"],
		_escData["/data/ru/male_patronymics"],
		_escData["/data/ru/months"],
		_escData["/data/ru/phones_format"],
		_escData["/data/ru/states"],
		_escData["/data/ru/streets"],
		_escData["/data/ru/weekdays"],
		_escData["/data/ru/weekdays_short"],
		_escData["/data/ru/zips_format"],
	},
}
